name = "LOTAC"
version = "0.1.0"
defaultTargets = ["LOTAC2", "textbook"]

[leanOptions]
verso.code.warnLineLength = 80

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.33.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "v4.33.0"

[[lean_lib]]
name = "LOTAC"

[[lean_lib]]
name = "LOTAC2"

[[lean_lib]]
name = "Textbook"
needs = ["references"]

[[lean_exe]]
name = "textbook"
root = "LOTAC2TextbookMain"

[[input_file]]
name = "references"
path = "references.bib"
text = true
