import Mathlib
import VersoManual
import Textbook.Blocks

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Textbook

set_option pp.rawOnError true

#doc (Manual) "Formulae" =>

# The Language of Modal Formulas
:::definition "Modal formulas"
Let $`Φ` be a denumerable set of atomic formulae.
```lean
variable (Φ : Type) [Denumerable Φ]
```
The type of modal formulae is defined inductively,
over atomic formulae, a falsity constant, an implication constructor $`→`,
and a necessity constructor $`\Box`.

```lean
inductive L where
| atom : Φ → L
| bot : L
| imp : L → L → L
| box : L → L
deriving Inhabited
```
The set of all formulae generated by $`Φ` is denoted by $`Fma(Φ)`.
```lean
def Fma : Set (L Φ) := Set.univ
```
In lean we will subscript term constructors and notations with $`ₜ` to avoid
name clashes with the meta-language, but outside of lean we will omit the
subscript.
```lean
notation "⊥ₜ" => L.bot
infixr:30 " →ₜ " => L.imp
prefix:max " □ₜ" => L.box
```
We define the remaining connectives in terms of the primitive ones.
```lean
def L.not {Φ : Type} (A : L Φ) : L Φ := A →ₜ ⊥ₜ
prefix:max " ¬ₜ" => L.not

def L.top {Φ : Type} : L Φ := ¬ₜ⊥ₜ
notation "⊤ₜ" => L.top

def L.and {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(A →ₜ ¬ₜB)
infixr:35 " ∧ₜ " => L.and

def L.or {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(¬ₜA ∧ₜ ¬ₜB)
infixr:30 "∨ₜ " => L.or

def L.iff {Φ : Type} (A B : L Φ) : L Φ := (A →ₜ B) ∧ₜ (B →ₜ A)
infixr:25 " ↔ₜ " => L.iff

def L.dia {Φ : Type} (A : L Φ) : L Φ := ¬ₜ□ₜ¬ₜA
prefix:max "◇ₜ" => L.dia
```
:::

:::details "Lean notation and printing support"

For constructive examples we need a concrete type for atomic formulae.
We will use the type of strings as our set of  atomic formulae, that is
$`Φ := String`. This implementation support lets examples use strings directly
as atoms and makes the interpreter print formulae using object-language
notation. To this end we define a `Repr` instance for formulae,
which allows us to print formulae in the lean interpreter.
We also define a coercion from strings to atomic formulae, so that we can
write formulas using strings directly, with an underlying macro to help.
```lean
def L.formatPrec {Φ : Type} [Repr Φ] : L Φ → Nat → Std.Format
  | .atom p, prec => reprPrec p prec
  | .bot, _ => "⊥ₜ"
  | .imp A B, prec =>
    let out := L.formatPrec A 31 ++ " →ₜ " ++ L.formatPrec B 30
    if prec > 30 then Std.Format.bracket "(" out ")" else out
  | .box A, _ => "□ₜ" ++ L.formatPrec A 1024

instance {Φ : Type} [Repr Φ] : Repr (L Φ) where
  reprPrec := L.formatPrec

instance : CoeHTCT String (L String) where
  coe := L.atom

syntax:31 str " →ₜ " term:30 : term
macro_rules
  | `($p:str →ₜ $A:term) => `(L.atom $p →ₜ $A)

syntax:36 str " ∧ₜ " term:35 : term
macro_rules
  | `($p:str ∧ₜ $A:term) => `(L.atom $p ∧ₜ $A)
```
:::
For constructive examples we will use Strings as our set of atomic formulae,
that is $`Φ := String`.

With this we can write the formula $`□(p → q)` as
```lean
#check □ₜ("p" →ₜ "q")
```
Or a more complex formulae such as $`□(p → q) ∧ □(q → r)` as
```lean
#check □ₜ("p" →ₜ "q") ∧ₜ □ₜ("q" →ₜ "r")
```

:::details "Decidable equality Of Formulae"
In order to define things like subformulae we need decidable equality on
formulae. First we have that from the denumberability of $`Φ` we can derive
decidable equality on $`Φ` and $`L Φ`. Decidable equality is a property of a
type that says we have an algorithm to decide whether two elements of said type
are equal or not. We use the `Encodable` typeclass to derive decidable
equality on $`Φ` and $`L Φ`.

```lean
instance : DecidableEq Φ := Encodable.decidableEqOfEncodable Φ
deriving instance DecidableEq, BEq for L
```
With decidable equality in place we have the ability to take unions
and intersections of finite sets of formulae. We will use the `Finset` type to
represent finite sets of formulae. We can also derive a `Repr` instance for
formulae, which allows us to print formulae in the lean interpreter.
:::

:::definition "Subformulae"
The finite set of subformulae of a formula $`A` is defined inductively as:
```lean
def L.subformulae {Φ : Type} [DecidableEq Φ] : L Φ → Finset (L Φ)
| L.atom p => {L.atom p}
| L.bot => {L.bot}
| L.imp A B => {L.imp A B} ∪ L.subformulae A ∪ L.subformulae B
| L.box A => {L.box A} ∪ L.subformulae A
```
We use a prefix S to denote the set of subformulae of a formula, so that $`S[A]`
is the set of all subformulae of $`A`.
```lean
notation "S[" A "]" => L.subformulae A
```

:::

For example the subformulae of $`□(p → q)` are
$`\{□(p → q), p → q, p, q\}`.
```leanEval
#eval S[ □ₜ("p" →ₜ "q") ]
```

We will often want to discuss Schemata, collections of formulae that share
a common syntactic form. For example "the schema $`□(A → A)`" is the collection
of all formulae of the form $`□(A → A)` for any formula $`A`. In set builder
notation we can write this as $`\{□(A → A) \mid A \in Fma(Φ)\}`.

The notion of schema is formalized using uniform substitutions. A uniform
substitution is a function that replaces atomic formulae with arbitrary
formulae. For example the uniform substitution $`σ` defined by $`σ(p) := □p`
and $`σ(q) := q ∨ r` replaces the atomic formula $`p` with $`□p` and
the atomic formula $`q` with $`q ∨ r`. The result of applying this uniform
substitution to the schema $`□(A → A)` is the formula $`□(□p → □p)`.

:::definition "Uniform Substitutions"
A uniform substitution is a function $`σ : Φ → Fma(Φ)` that replaces
atomic formulae with arbitrary formulae. The result of applying a uniform
substitution $`σ` to a formula $`A` is denoted by $`σ(A)` and is defined
inductively as follows:
```lean
def L.subst {Φ : Type} [DecidableEq Φ] (σ : Φ → L Φ) : L Φ → L Φ
| L.atom p => σ p
| L.bot => L.bot
| L.imp A B => L.imp (L.subst σ A) (L.subst σ B)
| L.box A => L.box (L.subst σ A)
```
Note that this definition is *simultaneous*, meaning that all atomic formulae
are replaced at once, rather than sequentially.

A formula $`A'` is said to be a substitution instance of a formula $`A` if it
can be obtained by simultaineously substituting some of the atomic formulae
in $`A` with arbitrary formulae. In otherwords, $`A'` is a substitution instance
of $`A` if there exists a uniform substitution $`σ` such that $`A' = σ(A)`.
```lean
def L.isSubstInstance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) : Prop :=
  ∃ σ : Φ → L Φ, A' = L.subst σ A
```
:::
With this we can define a schema as the set of all substitution instances
of a formula.
:::definition "Schema"
The schema generated by a formula $`A` is the set of all substitution instances
of $`A`, denoted by $`\operatorname{Schema}(A)`.
```lean
def L.schema {Φ : Type} [DecidableEq Φ] (A : L Φ) : Set (L Φ) :=
  {A' | L.isSubstInstance A' A}
```
:::

Deciding membership in a schema is decidable. We provide a non-trivial algorithm
for interested readers in the collapsable section.

:::details "Decidability of Schema membership"
We can show that membership in a schema is decidable. That is, given a formula
$`A` and a formula $`A'`, we can decide whether $`A'` is a substitution instance
of $`A`. The decision procedure traverses $`A` and $`A'` together while storing
the formula assigned to each atom of $`A`. If the same atom occurs again, its
new target must agree with the assignment already stored.
```lean
abbrev L.SubstMap (Φ : Type) := Φ → Option (L Φ)

def L.SubstMap.Extends {Φ : Type} (τ σ : L.SubstMap Φ) : Prop :=
  ∀ p B, σ p = some B → τ p = some B

def L.SubstMap.Agrees {Φ : Type}
    (τ : L.SubstMap Φ) (σ : Φ → L Φ) : Prop :=
  ∀ p B, τ p = some B → σ p = B

def L.matchSubst {Φ : Type} [DecidableEq Φ] :
    L Φ → L Φ → L.SubstMap Φ → Option (L.SubstMap Φ)
  | .atom p, B, τ =>
      match τ p with
      | some C => if C = B then some τ else none
      | none => some fun q => if q = p then some B else τ q
  | .bot, .bot, τ => some τ
  | .imp A₁ A₂, .imp B₁ B₂, τ => do
      let τ ← L.matchSubst A₁ B₁ τ
      L.matchSubst A₂ B₂ τ
  | .box A, .box B, τ => L.matchSubst A B τ
  | _, _, _ => none
```

The matcher never changes an assignment that it has already made.

```lean
theorem L.matchSubst_extends {Φ : Type} [DecidableEq Φ]
    {A B : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst A B τ = some τ') : τ'.Extends τ := by
  induction A generalizing B τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h <;> simp_all [L.SubstMap.Extends]
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        intro q C hq
        by_cases heq : q = p
        · simp only [heq, if_pos]
          subst q
          simp_all
        · simp [heq, hq]
  | bot =>
      cases B <;> simp_all [L.matchSubst, L.SubstMap.Extends]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases B with
      | imp B₁ B₂ =>
          cases h₁ : L.matchSubst A₁ B₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            intro p C hp
            exact ih₂ h p C (ih₁ h₁ p C hp)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases B <;> simp_all [L.matchSubst]
      exact ih h
```

The next two results prove that matching is sound and complete with respect
to uniform substitution.

```lean
theorem L.matchSubst_sound {Φ : Type} [DecidableEq Φ]
    {A B : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst A B τ = some τ') {σ : Φ → L Φ}
    (hagrees : τ'.Agrees σ) : L.subst σ A = B := by
  induction A generalizing B τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h
        · rename_i heq
          simp_all [L.subst, L.SubstMap.Agrees]
        · simp_all
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        simp only [L.subst]
        apply hagrees p B
        simp
  | bot => cases B <;> simp_all [L.matchSubst, L.subst]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases B with
      | imp B₁ B₂ =>
          cases h₁ : L.matchSubst A₁ B₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            have hext := L.matchSubst_extends h
            have hagrees₁ : τ₁.Agrees σ := fun p C hp =>
              hagrees p C (hext p C hp)
            exact congrArg₂ L.imp
              (ih₁ h₁ hagrees₁) (ih₂ h hagrees)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases B with
      | box B => exact congrArg L.box (ih h hagrees)
      | _ => simp_all [L.matchSubst]

theorem L.matchSubst_complete {Φ : Type} [DecidableEq Φ]
    {A B : L Φ} {τ : L.SubstMap Φ} {σ : Φ → L Φ}
    (hagrees : τ.Agrees σ) (hsubst : L.subst σ A = B) :
    ∃ τ', L.matchSubst A B τ = some τ' ∧ τ'.Agrees σ := by
  induction A generalizing B τ with
  | atom p =>
      simp only [L.subst] at hsubst
      subst B
      simp only [L.matchSubst]
      split
      · rename_i C hC
        have hσ := hagrees p C hC
        subst C
        simp [hagrees]
      · rename_i hnone
        refine ⟨fun q => if q = p then some (σ p) else τ q, ?_, ?_⟩
        · simp
        · intro q C hq
          simp only at hq
          split at hq
          · simp_all
          · exact hagrees q C hq
  | bot =>
      simp only [L.subst] at hsubst
      subst B
      exact ⟨τ, rfl, hagrees⟩
  | imp A₁ A₂ ih₁ ih₂ =>
      cases B with
      | imp B₁ B₂ =>
          simp only [L.subst, L.imp.injEq] at hsubst
          obtain ⟨τ₁, h₁, hagrees₁⟩ := ih₁ hagrees hsubst.1
          obtain ⟨τ₂, h₂, hagrees₂⟩ := ih₂ hagrees₁ hsubst.2
          exact ⟨τ₂, by simp [L.matchSubst, h₁, h₂], hagrees₂⟩
      | _ => simp_all [L.subst]
  | box A ih =>
      cases B with
      | box B =>
          simp only [L.subst, L.box.injEq] at hsubst
          obtain ⟨τ', h, hagrees'⟩ := ih hagrees hsubst
          exact ⟨τ', h, hagrees'⟩
      | _ => simp_all [L.subst]
```

Starting the matcher with an empty partial substitution therefore decides
whether $`A'` is a substitution instance of $`A`.

```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
    Decidable (L.isSubstInstance A' A) := by
  let empty : L.SubstMap Φ := fun _ => none
  match h : L.matchSubst A A' empty with
  | some τ =>
      apply isTrue
      let σ : Φ → L Φ := fun p => (τ p).getD (.atom p)
      refine ⟨σ, ?_⟩
      symm
      apply L.matchSubst_sound h
      intro p B hp
      simp [σ, hp]
  | none =>
      apply isFalse
      rintro ⟨σ, hσ⟩
      have hagrees : empty.Agrees σ := by
        simp [empty, L.SubstMap.Agrees]
      obtain ⟨τ, hτ, _⟩ :=
        L.matchSubst_complete hagrees hσ.symm
      simp_all
```

For example, replacing $`p` uniformly by $`q` succeeds, whereas replacing its
two occurrences by different formulae does not.

```leanEval
#eval decide (L.isSubstInstance ("q" →ₜ "q") ("p" →ₜ "p"))
#eval decide (L.isSubstInstance ("q" →ₜ "r") ("p" →ₜ "p"))
```

We thus have membership in a schema is decidable, since $`A'` is a
substitution instance of $`A` if and only if the matcher succeeds.
```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
    Decidable (A' ∈ L.schema A) := by
  change Decidable (L.isSubstInstance A' A)
  infer_instance
```
:::

For example, the formula $`□(p → q)` is a substitution instance of the schema
$`□(A → B)` by substituting $`p` for $`A` and $`q` for $`B`.
```leanEval
#eval (□ₜ("p" →ₜ "q") ∈ L.schema (□ₜ("A" →ₜ "B")))
```
A more complex example is that the formula $`□(p → (q ∧ r)) ∧ □(p → ¬(q ∧ r))` is a
substitution instance of the schema $`□(A → B) ∧ □(A → ¬B)` by substituting
$`p` for $`A` and $`q ∧ r` for $`B`.
```leanEval
#eval ((□ₜ("p" →ₜ ("q" ∧ₜ "r")) ∧ₜ □ₜ("p" →ₜ ¬ₜ("q" ∧ₜ "r")))
  ∈ L.schema (□ₜ("A" →ₜ "B") ∧ₜ □ₜ("A" →ₜ ¬ₜ"B")))
```
