import Mathlib
import VersoManual
import Textbook.Blocks

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Textbook

set_option pp.rawOnError true

#doc (Manual) "Propositional Modal Logic" =>

# The Language of Modal Formulae

:::definition "Modal formulas"
Let $`Φ` be a denumerable {margin}[`Denumerable` just meaning it has a
one-to-one correspondence with `ℕ`. Mathlib has good built in support for
denumerable types.] set of atomic formulae.
```lean
variable (Φ : Type) [Denumerable Φ]
```
The type of modal formulae is defined inductively,
over atomic formulae, a falsity constant, an implication constructor $`→`,
and a necessity constructor $`\Box` (This presentation is taken from
{citet Goldblatt1992}[]). Using BNF notation, we write the grammar
for formulae as follows where $`p ∈ Φ`:
$$`φ ::= p | ⊥ | φ → φ | □φ`
In lean we define formula as an inducutive type `L Φ`. An inductive type is
a type that is defined by a set of constructors that generate all the elements
of the type. In this case, the constructors are `atom`, `bot`, `imp`, and `box`.
The type of formulae is parameterized by the type of atomic formula $`Φ`.
```lean
--note we ommit the Φ parameter since it is declared as a variable above
inductive L where
| atom : Φ → L
| bot : L
| imp : L → L → L
| box : L → L
deriving Inhabited, Encodable
```
:::

With this type in place we can write formulae in lean using the constructors.
For example, the formula $`□p → q` can be written in lean as
```lean
#check L.imp (L.box (L.atom "p")) (L.atom "q")
```
Note "p" and "q" have the type `String`, which is Denumerable, so we can use
them as atomic formulae.

Writing formulae using the constructors directly as above is cumbersome, we want
to write formulae in lean the same way we write them in the object language.
Lean allows us to define custom notations for types, so we define notations
for the constructors.{margin}[In Lean we will subscript term constructors and
notations with `ₜ` to avoid name clashes with the meta-language (Lean is very
particular with its logical connectives `∧`, `∨`, `¬`, `→`, and `↔` and they do
not support easy overloading) Outside of Lean we will omit the subscript, and
meta-language usage will always be clear from context.]

```lean
notation "⊥ₜ" => L.bot
infixr:30 " →ₜ " => L.imp
prefix:max " □ₜ" => L.box
postfix:max "ᵃ" => L.atom
```

Now we can write the formula $`□p → q` in lean as
```lean
#check □ₜ"p"ᵃ →ₜ "q"ᵃ
```

:::definition "Other Connectives"

At this point, readers familar with modal or even propositional logic will
notice that we are missing some familiar logical connectives. We define the
language to be a minimal *functionally complete*{margin}[meaning that all other
connectives can be defined in terms of this minimal set.] set of connectives.
We define the remaining connectives in terms of the primitive ones.
$$`
\begin{aligned}
¬φ &:= φ → ⊥ \\
⊤ &:= ¬⊥ \\
φ ∧ ψ &:= ¬(φ → ¬ψ) \\
φ ∨ ψ &:= ¬(¬φ ∧ ¬ψ) \\
φ ↔ ψ &:= (φ → ψ) ∧ (ψ → φ)
\end{aligned}
`

```lean
@[simp]
def L.not {Φ : Type} (A : L Φ) : L Φ := A →ₜ ⊥ₜ
prefix:max " ¬ₜ" => L.not

@[simp]
def L.top {Φ : Type} : L Φ := ¬ₜ⊥ₜ
notation "⊤ₜ" => L.top

@[simp]
def L.and {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(A →ₜ ¬ₜB)
infixr:35 " ∧ₜ " => L.and

@[simp]
def L.or {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(¬ₜA ∧ₜ ¬ₜB)
infixr:30 "∨ₜ " => L.or

@[simp]
def L.iff {Φ : Type} (A B : L Φ) : L Φ := (A →ₜ B) ∧ₜ (B →ₜ A)
infixr:25 " ↔ₜ " => L.iff

@[simp]
def L.dia {Φ : Type} (A : L Φ) : L Φ := ¬ₜ□ₜ¬ₜA
prefix:max "◇ₜ" => L.dia
```
:::

:::definition "Set of Formulae"
The set of all formulae generated by $`Φ` is denoted by $`Fma(Φ)`.
```lean
abbrev Fma : Set (L Φ) := Set.univ
```
:::

:::details "Lean notation and printing support"

For constructive examples we need a concrete type for atomic formulae.
We will use the type of strings as our set of  atomic formulae, that is
$`Φ := String`. This implementation support lets examples use strings directly
as atoms and makes the interpreter print formulae using object-language
notation. To this end we define a `Repr` instance for formulae,
which allows us to print formulae in the lean interpreter.
We also define a coercion from strings to atomic formulae, so that we can
write formulas using strings directly, with an underlying macro to help.
```lean
def L.formatPrec {Φ : Type} [Repr Φ] : L Φ → Nat → Std.Format
  | .atom p, prec => reprPrec p prec
  | .bot, _ => "⊥ₜ"
  | .imp A B, prec =>
    let out := L.formatPrec A 31 ++ " →ₜ " ++ L.formatPrec B 30
    if prec > 30 then Std.Format.bracket "(" out ")" else out
  | .box A, _ => "□ₜ" ++ L.formatPrec A 1024

instance {Φ : Type} [Repr Φ] : Repr (L Φ) where
  reprPrec := L.formatPrec

instance : CoeHTCT String (L String) where
  coe := L.atom

syntax:31 str " →ₜ " term:30 : term
macro_rules
  | `($p:str →ₜ $A:term) => `(L.atom $p →ₜ $A)

syntax:36 str " ∧ₜ " term:35 : term
macro_rules
  | `($p:str ∧ₜ $A:term) => `(L.atom $p ∧ₜ $A)
```
:::
For constructive examples we will use `String` as our set of atomic formulae,
that is $`Φ :=` `String`.

With this we can write the formula $`□(p → q)` as
```lean
#check □ₜ("p" →ₜ "q")
```
Or a more complex formulae such as $`□(p → q) ∧ □(q → r)` as
```lean
#check □ₜ("p" →ₜ "q") ∧ₜ □ₜ("q" →ₜ "r")
```

:::details "Decidable equality Of Formulae"
In order to define things like subformulae we need decidable equality on
formulae. First we have that from the denumberability of $`Φ` we can derive
decidable equality on $`Φ` and $`L Φ`. Decidable equality is a property of a
type that says we have an algorithm to decide whether two elements of said type
are equal or not. We use the `Encodable` typeclass to derive decidable
equality on $`Φ` and $`L Φ`.

```lean
instance : DecidableEq Φ := Encodable.decidableEqOfEncodable Φ
deriving instance DecidableEq, BEq for L
```
With decidable equality in place we have the ability to take unions
and intersections of finite sets of formulae. We will use the `Finset` type to
represent finite sets of formulae. We can also derive a `Repr` instance for
formulae, which allows us to print formulae in the lean interpreter.
:::

# Subformulae, Substitution, and Schemata

:::definition "Subformulae"
The finite set of subformulae of a formula $`A` is defined inductively as:
```lean
@[simp]
def L.subformulae {Φ : Type} [DecidableEq Φ] : L Φ → Finset (L Φ)
| L.atom p => {L.atom p}
| L.bot => {L.bot}
| L.imp A B => {L.imp A B} ∪ L.subformulae A ∪ L.subformulae B
| L.box A => {L.box A} ∪ L.subformulae A
```
We use a prefix S to denote the set of subformulae of a formula, so that $`S[A]`
is the set of all subformulae of $`A`.
```lean
notation "S[" A "]" => L.subformulae A
```

:::

For example the subformulae of $`□(p → q)` are
$`\{□(p → q), p → q, p, q\}`.
```leanEval
#eval S[ □ₜ("p" →ₜ "q") ]
```

:::details "Properties of Subformulae"
A formula is always a subformula of itself.
i.e. membership of subformulae is reflexive.
```lean
@[simp]
theorem L.subformulae_mem_refl (A : L Φ) : A ∈ S[A] := by
  induction A
  case atom p => simp only [L.subformulae, Finset.mem_singleton]
  case bot => simp only [L.subformulae, Finset.mem_singleton]
  case imp A B ihA ihB =>
    simp only [L.subformulae, Finset.singleton_union, Finset.insert_union,
    Finset.mem_insert, Finset.mem_union, true_or]
  case box A ih =>
    simp only [L.subformulae, Finset.singleton_union, Finset.mem_insert,
    true_or]
```
Membership of subformulae is transitive.
```lean
@[simp]
theorem L.subformulae_mem_trans (A B C: L Φ) :
B ∈ S[A] → C ∈ S[B] → C ∈ S[A] := by
  induction A generalizing B C <;> aesop
```

:::

We will often want to discuss Schemata, collections of formulae that share
a common syntactic form. For example "the schema $`□(φ → φ)`" is the collection
of all formulae of the form $`□(φ → φ)` for any formula $`φ`. In set builder
notation we can write this as $`\{□(φ → φ) \mid φ \in Fma(Φ)\}`.

The notion of schema is formalized using uniform substitutions. A uniform
substitution is a function that replaces atomic formulae with arbitrary
formulae. For example the uniform substitution $`σ` defined by $`σ(p) := □p`
and $`σ(q) := q ∨ r` replaces the atomic formula $`p` with $`□p` and
the atomic formula $`q` with $`q ∨ r`. The result of applying this uniform
substitution to the schema $`□(A → A)` is the formula $`□(□p → □p)`.

:::definition "Uniform Substitutions"
A uniform substitution is a function $`σ : Φ → Fma(Φ)` that replaces
atomic formulae with arbitrary formulae. The result of applying a uniform
substitution $`σ` to a formula $`φ` is denoted by $`φ /ₛ σ` and is defined
inductively as follows:
```lean
def L.subst {Φ : Type} [DecidableEq Φ] (φ : L Φ) (σ : Φ → L Φ) : L Φ :=
match φ with
| L.atom p => σ p
| L.bot => L.bot
| L.imp φ₁ φ₂ => L.imp (L.subst φ₁ σ) (L.subst φ₂ σ)
| L.box φ₁ => L.box (L.subst φ₁ σ)

infixl:100 "/ₛ" => L.subst
```
Note that this definition is *simultaneous*, meaning that all atomic formulae
are replaced at once, rather than sequentially.

A formula $`φ'` is said to be a substitution instance of a formula $`φ` if it
can be obtained by simultaineously substituting some of the atomic formulae
in $`φ` with arbitrary formulae. In otherwords, $`φ'` is a substitution instance
of $`φ` if there exists a uniform substitution $`σ` such that $`φ' = σ(φ)`.
```lean
def L.isSubstInstance {Φ : Type} [DecidableEq Φ] (φ' φ : L Φ) : Prop :=
  ∃ σ : Φ → L Φ, φ' = φ /ₛ σ
```
:::
With this we can define a schema as the set of all substitution instances
of a formula.
:::definition "Schema"
The schema generated by a formula $`φ` is the set of all substitution instances
of $`φ`, denoted by $`\operatorname{Schema}(φ)`.
```lean

def L.schema {Φ : Type} [DecidableEq Φ] (φ : L Φ) : Set (L Φ) :=
  {φ' | L.isSubstInstance φ' φ}

```
In lean we denote a schema with the notation "\[φ\]ₛ" where
$`φ` is the formula that generates the schema.
```lean
notation "[" A "]ₛ" => L.schema A

theorem L.mem_schema_self {Ψ : Type} [DecidableEq Ψ] (φ : L Ψ) :
φ ∈ [φ]ₛ := by
  refine ⟨L.atom, ?_⟩
  induction φ with
  | atom _ => rfl
  | bot => rfl
  | imp φ₁ φ₂ ih₁ ih₂ =>
      exact congrArg₂ L.imp ih₁ ih₂
  | box φ₁ ih =>
      exact congrArg L.box ih
```
:::

## Decidability of Schema Membership

Membership of a concrete formula in a schema is decidable. i.e., given a formula
$`φ` and a formula $`ψ`, we have an algorithm to decide whether $`ψ` is a
substitution instance of $`φ`. We provide an algorithm for interested readers
and prove soundness and completeness.

The decision procedure traverses $`φ` and $`ψ` together while storing
the formula assigned to each atom of $`φ`. If the same atom occurs again, its
new target must agree with the assignment already stored.
```lean
abbrev L.SubstMap (Φ : Type) := Φ → Option (L Φ)

def L.SubstMap.Extends {Φ : Type} (τ σ : L.SubstMap Φ) : Prop :=
  ∀ p B, σ p = some B → τ p = some B

def L.SubstMap.Agrees {Φ : Type}
    (τ : L.SubstMap Φ) (σ : Φ → L Φ) : Prop :=
  ∀ p B, τ p = some B → σ p = B

def L.matchSubst {Φ : Type} [DecidableEq Φ] :
    L Φ → L Φ → L.SubstMap Φ → Option (L.SubstMap Φ)
  | .atom p, B, τ =>
      match τ p with
      | some C => if C = B then some τ else none
      | none => some fun q => if q = p then some B else τ q
  | .bot, .bot, τ => some τ
  | .imp A₁ A₂, .imp B₁ B₂, τ => do
      let τ ← L.matchSubst A₁ B₁ τ
      L.matchSubst A₂ B₂ τ
  | .box A, .box B, τ => L.matchSubst A B τ
  | _, _, _ => none
```

The matcher never changes an assignment that it has already made.

```lean
theorem L.matchSubst_extends {Φ : Type} [DecidableEq Φ]
    {A B : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst A B τ = some τ') : τ'.Extends τ := by
  induction A generalizing B τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h <;> simp_all [L.SubstMap.Extends]
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        intro q C hq
        by_cases heq : q = p
        · simp only [heq, if_pos]
          subst q
          simp_all
        · simp [heq, hq]
  | bot =>
      cases B <;> simp_all [L.matchSubst, L.SubstMap.Extends]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases B with
      | imp B₁ B₂ =>
          cases h₁ : L.matchSubst A₁ B₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            intro p C hp
            exact ih₂ h p C (ih₁ h₁ p C hp)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases B <;> simp_all [L.matchSubst]
      exact ih h
```

The next two results prove that matching is sound and complete with respect
to uniform substitution.

```lean
theorem L.matchSubst_sound {Φ : Type} [DecidableEq Φ]
    {φ ψ : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst φ ψ τ = some τ') {σ : Φ → L Φ}
    (hagrees : τ'.Agrees σ) : φ /ₛ σ = ψ := by
  induction φ generalizing ψ τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h
        · rename_i heq
          simp_all [L.SubstMap.Agrees, L.subst]
        · simp_all
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        simp only [L.subst]
        apply hagrees p ψ
        simp
  | bot => cases ψ <;> simp_all [L.matchSubst, L.subst]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases ψ with
      | imp ψ₁ ψ₂ =>
          cases h₁ : L.matchSubst A₁ ψ₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            have hext := L.matchSubst_extends h
            have hagrees₁ : τ₁.Agrees σ := fun p C hp =>
              hagrees p C (hext p C hp)
            exact congrArg₂ L.imp
              (ih₁ h₁ hagrees₁) (ih₂ h hagrees)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases ψ with
      | box ψ => exact congrArg L.box (ih h hagrees)
      | _ => simp_all [L.matchSubst]

theorem L.matchSubst_complete {Φ : Type} [DecidableEq Φ]
{φ ψ : L Φ} {τ : L.SubstMap Φ} {σ : Φ → L Φ}
(hagrees : τ.Agrees σ) (hsubst : φ /ₛ σ = ψ) :
∃ τ', L.matchSubst φ ψ τ = some τ' ∧ τ'.Agrees σ := by
  induction φ generalizing ψ τ with
  | atom p =>
      simp only [L.subst] at hsubst
      subst ψ
      simp only [L.matchSubst]
      split
      · rename_i C hC
        have hσ := hagrees p C hC
        subst C
        simp [hagrees]
      · rename_i hnone
        refine ⟨fun q => if q = p then some (σ p) else τ q, ?_, ?_⟩
        · simp
        · intro q C hq
          simp only at hq
          split at hq
          · simp_all
          · exact hagrees q C hq
  | bot =>
      simp only [L.subst] at hsubst
      subst ψ
      exact ⟨τ, rfl, hagrees⟩
  | imp A₁ A₂ ih₁ ih₂ =>
      cases ψ with
      | imp ψ₁ ψ₂ =>
          simp only [L.subst, L.imp.injEq] at hsubst
          obtain ⟨τ₁, h₁, hagrees₁⟩ := ih₁ hagrees hsubst.1
          obtain ⟨τ₂, h₂, hagrees₂⟩ := ih₂ hagrees₁ hsubst.2
          exact ⟨τ₂, by simp [L.matchSubst, h₁, h₂], hagrees₂⟩
      | _ => simp_all [L.subst]
  | box A ih =>
      cases ψ with
      | box ψ =>
          simp only [L.subst, L.box.injEq] at hsubst
          obtain ⟨τ', h, hagrees'⟩ := ih hagrees hsubst
          exact ⟨τ', h, hagrees'⟩
      | _ => simp_all [L.subst]
```

Starting the matcher with an empty partial substitution therefore decides
whether $`A'` is a substitution instance of $`A`.

```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
    Decidable (L.isSubstInstance A' A) := by
  let empty : L.SubstMap Φ := fun _ => none
  match h : L.matchSubst A A' empty with
  | some τ =>
      apply isTrue
      let σ : Φ → L Φ := fun p => (τ p).getD (.atom p)
      refine ⟨σ, ?_⟩
      symm
      apply L.matchSubst_sound h
      intro p B hp
      simp [σ, hp]
  | none =>
      apply isFalse
      rintro ⟨σ, hσ⟩
      have hagrees : empty.Agrees σ := by
        simp [empty, L.SubstMap.Agrees]
      obtain ⟨τ, hτ, _⟩ :=
        L.matchSubst_complete hagrees hσ.symm
      simp_all
```

For example, replacing $`p` uniformly by $`q` succeeds, whereas replacing its
two occurrences by different formulae does not.

```leanEval
#eval decide (L.isSubstInstance ("q" →ₜ "q") ("p" →ₜ "p"))
#eval decide (L.isSubstInstance ("q" →ₜ "r") ("p" →ₜ "p"))
```

We thus have membership in a schema is decidable, since $`A'` is a
substitution instance of $`A` if and only if the matcher succeeds.
```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
    Decidable (A' ∈ [A]ₛ) := by
  change Decidable (L.isSubstInstance A' A)
  infer_instance
```

For example, the formula $`□(p → q)` is a substitution instance of the schema
$`□(A → B)` by substituting $`p` for $`A` and $`q` for $`B`.
```leanEval
#eval (□ₜ("p" →ₜ "q") ∈ [□ₜ("A" →ₜ "B")]ₛ)
```
A more complex example is that the formula $`□(p → (q ∧ r)) ∧ □(p → ¬(q ∧ r))`
is a substitution instance of the schema $`□(A → B) ∧ □(A → ¬B)` by
substituting $`p` for $`A` and $`q ∧ r` for $`B`.
```leanEval
#eval ((□ₜ("p" →ₜ ("q" ∧ₜ "r")) ∧ₜ □ₜ("p" →ₜ ¬ₜ("q" ∧ₜ "r")))
  ∈ [□ₜ("A" →ₜ "B") ∧ₜ □ₜ("A" →ₜ ¬ₜ"B")]ₛ)
```

# Tautologies

An important class of formulae are tautologies, formulae that are true under
every valuation of their atomic propositions. In propositional logic,
defining tautologies is straightforward, as we are just dealing with valuations
on atomic propositions. In modal logic, however, we have to deal with the
additional complexity of the box operator. We follow {citet Goldblatt1992}[]
and define tautologies in terms of _quasi-atomic subformulae_, by treating
boxed formulae as a kind of atomic proposition. This allows us to define
tautologies in a way analogous to propositional logic.

:::definition "Quasi-atomic Formulae"
A formula is quasi-atomic if it is either atomic or begins with a box.
```lean
@[simp]
def L.isQuasiAtomic {Φ : Type} : L Φ → Prop
| .atom _ => True
| .box _ => True
| _ => False
```
:::

:::definition "Quasi-atomic Subformulae Valuations"
A Quasi-atomic subformula valuation is a valuation function that assigns
true or false to each quasi-atomic subformula of a formula.

```lean
abbrev QuasiAtomicSubformulaValuation (φ : L Φ) :=
  (ψ : L Φ) → ψ.isQuasiAtomic → ψ ∈ S[φ] → Prop

```
Given a quasi-atomic valuation `V`, we can extend it to a valuation of
an arbitrary formula `φ`. To do this, we need to be able to lift
valuations on implications to valuations on their left and right subformulae.
The following definitions provide this lifting.
```lean
/--
Given a quasi-atomic subformula valuation of an implication,
return a valuation over subformulae of the left-hand side of the implication.
 -/
def QuasiAtomicSubformulaValuation.left {φ ψ : L Φ}
(V : QuasiAtomicSubformulaValuation Φ (φ →ₜ ψ)) :
QuasiAtomicSubformulaValuation Φ φ :=
  fun χ hqa hχ => V χ hqa (by
    simp only [L.subformulae, Finset.mem_union,
      Finset.mem_singleton]
    exact Or.inl (Or.inr hχ))

def QuasiAtomicSubformulaValuation.right
{φ ψ : L Φ}
(V : QuasiAtomicSubformulaValuation Φ (φ →ₜ ψ)) :
QuasiAtomicSubformulaValuation Φ ψ :=
  fun χ hqa hχ => V χ hqa (by
    simp only [L.subformulae, Finset.mem_union,
      Finset.mem_singleton]
    exact Or.inr hχ)
```
With these we can then lift the valuation of quasi-atomic subformulae
to a valuation of entire formula.
```lean
def LiftedQuasiAtomicValuation
 (φ : L Φ) (V : QuasiAtomicSubformulaValuation Φ φ) : Prop :=
match h: φ with
| .atom p => V (.atom p)
  (by simp only [L.isQuasiAtomic])
  (by simp only [L.subformulae, Finset.mem_singleton])
| .box φ => V (.box φ)
  (by simp only [L.isQuasiAtomic])
  (by apply L.subformulae_mem_refl)
| .bot => False
| .imp φ ψ =>
  (LiftedQuasiAtomicValuation φ V.left) →
    (LiftedQuasiAtomicValuation ψ V.right)
```
:::

:::definition "Tautologies"
We define the notion of tautology in terms of quasi-atomic subformulae.
We say a formula φ is a tautology if its lifted valuation is true for
every valuation of its quasi-atomic subformula. This idea naturally
coresponds to the notion of tautology in propositional logic, where a formula
is a tautology if it is true under every assignment of truth values to
its propositional variables, except now we consider quasi-atomic subformulae
instead.
```lean
def L.isTautology (φ : L Φ) : Prop :=
  ∀ V : QuasiAtomicSubformulaValuation Φ φ, LiftedQuasiAtomicValuation Φ φ V
```
:::


A consequence of this is that any tautology is a subsitution instance of
a "box-free" tautology, i.e. a tautology in propositional logic.

```lean
@[simp]
def L.boxFree : L Φ → Prop
| .atom _ => True
| .bot => True
| .imp φ ψ => φ.boxFree ∧ ψ.boxFree
| .box _ => False
```

The proof replaces every quasi-atomic part of $`φ`—each atom and each boxed
subformula—by a fresh atomic name. Because $`Φ` is denumerable, formulae can be
encoded injectively as elements of $`Φ`; preserving $`⊥` and $`→` then produces
a box-free formula $`ψ`.

Every valuation of the new atoms in $`ψ` determines a valuation of the
corresponding quasi-atoms in $`φ`. A structural induction shows that $`ψ` and
$`φ` have the same truth value under these corresponding valuations, so the
tautologicity of $`φ` implies that of $`ψ`. Finally, substituting each fresh
name by the quasi-atomic formula it encodes reconstructs $`φ`, making $`φ` a
substitution instance of $`ψ`.
```lean
theorem L.subst_boxFree_tautology
(φ : L Φ) (hφ : φ.isTautology) :
∃ (ψ : L Φ), ψ.boxFree ∧ ψ.isTautology ∧ φ.isSubstInstance ψ := by
  classical
  let name (A : L Φ) := Denumerable.ofNat Φ (Encodable.encode A)
  let erase : L Φ → L Φ := L.rec
    (fun p => .atom (name (.atom p))) .bot
    (fun _ _ A B => A →ₜ B)
    (fun A _ => .atom (name (.box A)))
  let eval : L Φ → (L Φ → Prop) → Prop := L.rec
    (fun p V => V (.atom p)) (fun _ => False)
    (fun _ _ VA VB V => VA V → VB V)
    (fun A _ V => V (.box A))
  have congr : ∀ (A : L Φ) V W,
      (∀ B hq hB hB', V B hq hB = W B hq hB') →
      (LiftedQuasiAtomicValuation Φ A V ↔
        LiftedQuasiAtomicValuation Φ A W) := by
    intro A; induction A with
    | atom p => intros; exact iff_of_eq (by apply_assumption)
    | bot => simp [LiftedQuasiAtomicValuation]
    | box A => intros; exact iff_of_eq (by apply_assumption)
    | imp A B ihA ihB =>
        intro V W h
        simp only [LiftedQuasiAtomicValuation]
        rw [ihA V.left W.left, ihB V.right W.right]
        all_goals intros; apply h
  have total : ∀ (A : L Φ) (V : L Φ → Prop),
      LiftedQuasiAtomicValuation Φ A (fun B _ _ => V B) ↔ eval A V := by
    intro A; induction A with
    | atom p => intro V; rfl
    | bot => intro V; rfl
    | box A => intro V; rfl
    | imp A B ihA ihB =>
        intro V
        simp only [LiftedQuasiAtomicValuation, eval]
        rw [congr A _ (fun C _ _ => V C),
          congr B _ (fun C _ _ => V C), ihA, ihB]
        all_goals intros; rfl
  have free : ∀ A, (erase A).boxFree := by
    intro A; induction A <;> simp_all [erase]
  have rename : ∀ A V, eval (erase A) V ↔
      eval A (fun B => V (.atom (name B))) := by
    intro A; induction A <;> simp_all [erase, eval]
  have subst : ∀ A, A = L.subst (erase A)
    (fun p => (Encodable.decode (Encodable.encode p)).getD (L.atom p)) := by
    intro A; induction A with
    | atom p =>
        simp [erase, name, L.subst, Denumerable.encode_ofNat]
    | bot => rfl
    | imp A B ihA ihB =>
        simp only [erase, L.subst, L.imp.injEq]
        exact ⟨ihA, ihB⟩
    | box A =>
        simp [erase, name, L.subst, Denumerable.encode_ofNat]
  refine ⟨erase φ, free φ, ?_, ⟨_, subst φ⟩⟩
  · intro W
    let V : L Φ → Prop := fun A =>
      if hqa : A.isQuasiAtomic then
        if hA : A ∈ (erase φ).subformulae then W A hqa hA
        else False
      else False
    rw [congr _ W (fun A _ _ => V A)]
    · rw [total, rename, ← total]
      exact hφ (fun A _ _ => V (.atom (name A)))
    · intro A hqa hA hA'
      simp only [V, dif_pos hqa, dif_pos hA]
```
