import Mathlib
import VersoManual
import Textbook.Blocks

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Textbook

set_option pp.rawOnError true

#doc (Manual) "Formulae" =>

# The Language of Modal Formulas

Modal formulas are built from numbered propositional atoms, falsity, implication, and necessity.
The remaining familiar connectives are abbreviations. In the lean code we subscript term
constructors and notations with $`ₜ` to avoid name clashes with the meta-language.

:::definition "Modal formulas"
The set $`\mathcal L` of modal formulas is generated by
$$`
  A ::= p_n \mid \bot \mid (A \to B) \mid \Box A,
`
where $`n \in \mathbb N`.

```lean
inductive L where
  | atom : Nat → L
  | bot : L
  | imp : L → L → L
  | box : L → L
deriving DecidableEq, BEq, Inhabited, Repr, Encodable, ReflBEq, LawfulBEq

notation "⊥ₜ" => L.bot
infixr:30 " →ₜ " => L.imp
prefix:max " □ₜ" => L.box
```
:::

## Derived Connectives
We define the remaining connectives in terms of the primitive ones.

:::definition "Negation"
For every $`A \in \mathcal L`, define $`\neg A := A \to \bot.`

```lean
@[simp]
def L.not (A : L) : L := A →ₜ ⊥ₜ
prefix:max " ¬ₜ" => L.not
```
:::

:::definition "Truth"
Truth is the formula $`\top := \neg\bot.`

```lean
@[simp]
def L.top : L := ¬ₜ⊥ₜ
notation "⊤ₜ" => L.top
```
:::

:::definition "Disjunction"
For $`A,B \in \mathcal L`, define $`A \lor B := \neg A \to B.`

```lean
@[simp]
def L.or (A B : L) : L := ¬ₜA →ₜ B
infixl:35 "∨ₜ" => L.or
```
:::

:::definition "Conjunction"
For $`A,B \in \mathcal L`, define $`A \land B := \neg(A \to \neg B).`

```lean
@[simp]
def L.and (A B : L) : L := ¬ₜ(A →ₜ ¬ₜB)
infixl:40 "∧ₜ" => L.and
```
:::

:::definition "Biconditional"
For $`A,B \in \mathcal L`, define
$`A \leftrightarrow B := (A \to B) \land (B \to A).`

```lean
@[simp]
def L.iff (A B : L) : L := (A →ₜ B) ∧ₜ (B →ₜ A)
infix:20 "↔ₜ" => L.iff
```
:::

:::definition "Possibility"
For every $`A \in \mathcal L`, define $`\Diamond A := \neg\Box\neg A.`

```lean
@[simp]
def L.dia (A : L) : L := ¬ₜ□ₜ¬ₜA
prefix:max " ◇ₜ" => L.dia
```
:::

:::theorem "No formula is its own necessitation"
For every $`A \in \mathcal L`, $`A \ne \Box A.`

```lean
@[simp]
theorem a_neq_box_a : A ≠ □ₜA := by
  induction A <;> simp_all
```
:::

## Subformulae

:::definition "Subformulae set"
The finite set $`S(A)` of subformulae is defined recursively by
$$`
\begin{aligned}
S(p_n) &= \{p_n\}, & S(\bot) &= \{\bot\},\\
S(A\to B) &= \{A\to B\}\cup S(A)\cup S(B), &
S(\Box A) &= \{\Box A\}\cup S(A).
\end{aligned}
`

```lean
@[simp]
def S : L → Finset L
  | .atom p => {.atom p}
  | ⊥ₜ => {⊥ₜ}
  | A →ₜ B => {A →ₜ B} ∪ S A ∪ S B
  | □ₜA => {□ₜA} ∪ S A
```
:::

:::definition "Distinguished atoms"
The atoms used as schema variables are
$$`A_1 := p_1,\qquad A_2 := p_2,\qquad A_3 := p_3.`

```lean
@[simp] abbrev A1 : L := L.atom 1
@[simp] abbrev A2 : L := L.atom 2
@[simp] abbrev A3 : L := L.atom 3
```
:::

:::theorem "Reflexivity of subformulas"
For every $`A \in \mathcal L`,
$$`A \in S(A).`

```lean
theorem A_mem_S_A {A : L} : A ∈ S A := by
  induction A <;> aesop
```
:::

:::theorem "Transitivity of subformulas"
For all $`A,B,C \in \mathcal L`,
$$`A\in S(B) \land B\in S(C) \implies A\in S(C).`

```lean
theorem mem_S_trans {A B C : L} : A ∈ S B ∧ B ∈ S C → A ∈ S C := by
  intro ⟨H1, H2⟩
  induction B <;> induction C <;> simp_all only [S] <;> grind
```
:::

:::theorem "Subformulae of an implication"
For all $`A,B,C \in \mathcal L`,
$`A\to B \in S(C) \implies A\in S(C) \land B\in S(C).`

```lean
theorem mem_imp_mem {A B C : L} : (A →ₜ B) ∈ S C → A ∈ S C ∧ B ∈ S C := by
  induction C <;> simp_all only [S] <;> try grind [A_mem_S_A]
```
:::

## Substitution and Schemas

:::definition "Substitution"
Writing $`A[B/p]` for the replacement of the atom $`p` by $`B` in $`A`, define
$$`
\begin{aligned}
p'[B/p] &= \begin{cases}B & p=p',\\p'&p\ne p',\end{cases} &
\bot[B/p] &= \bot,\\
(A_1\to A_2)[B/p] &= A_1[B/p]\to A_2[B/p], &
(\Box A_1)[B/p] &= \Box(A_1[B/p]).
\end{aligned}
`

```lean
@[simp]
def subst (A B : L) (p : Nat) : L :=
  match A with
  | .atom q => if p = q then B else .atom q
  | ⊥ₜ => ⊥ₜ
  | A1 →ₜ A2 => subst A1 B p →ₜ subst A2 B p
  | □ₜA1 => □ₜ(subst A1 B p)
```
:::

:::definition "Multiple substitution"
For a list $`\sigma=[(p_1,B_1),\ldots,(p_n,B_n)]`, define
$$`A\sigma := A[B_1/p_1]\cdots[B_n/p_n],`
with substitutions applied from left to right.

```lean
@[simp]
def msubst (A : L) : List (Nat × L) → L
  | [] => A
  | (p, B) :: t => msubst (subst A B p) t
```
:::

:::definition "Substitution instance"
A formula $`A'` is a substitution instance of $`A` precisely when
$$`A \preceq_{\mathrm{sub}} A' \iff \exists\sigma,\ A\sigma=A'.`

```lean
@[simp]
def subst_inst (A A' : L) : Prop :=
  ∃ l : List (Nat × L), msubst A l = A'
```
:::

:::definition "Schema"
The schema generated by $`A` is
$$`\operatorname{Schema}(A):=\{A'\in\mathcal L\mid A\preceq_{\mathrm{sub}}A'\}.`

```lean
@[simp]
def Schema (A : L) : Set L :=
  {A' | subst_inst A A'}
```
:::

:::theorem "A formula belongs to its schema"
For every $`A \in \mathcal L`,
$$`A\in\operatorname{Schema}(A).`

```lean
theorem A_in_Schema_A : A ∈ Schema A := by
  use []
  simp
```
:::

## Quasi-Atoms and Valuations

:::definition "Boxed formulas"
The predicate $`\operatorname{isBox}` is given by
$$`\operatorname{isBox}(A)=\begin{cases}\mathsf{true}&A=\Box B,\\
\mathsf{false}&\text{otherwise.}\end{cases}`

```lean
@[simp]
def L.isBox : L → Bool
  | □ₜ_ => true
  | _ => false
```
:::

:::definition "Containing a box"
The Boolean predicate $`\operatorname{containsBox}` recursively records whether a formula has a
boxed subformula:
$$`
\begin{aligned}
c(p_n)&=\mathsf{false}, & c(\bot)&=\mathsf{false},\\
c(A\to B)&=c(A)\lor c(B), & c(\Box A)&=\mathsf{true}.
\end{aligned}`

```lean
@[simp]
def L.containsBox : L → Bool
  | .atom _ => false
  | ⊥ₜ => false
  | A →ₜ B => A.containsBox || B.containsBox
  | □ₜ_ => true
```
:::

:::theorem "Characterization of formulas containing a box"
For every $`A \in \mathcal L`,
$$`\operatorname{containsBox}(A) \iff
  \exists B\in S(A),\ \operatorname{isBox}(B).`

```lean
theorem containsBox_iff_mem_S_isBox (A : L) :
    A.containsBox ↔ ∃ B ∈ S A, B.isBox := by
  induction A
  case atom => simp
  case bot => simp
  case imp f1 f2 ih1 ih2 =>
    simp [-L.isBox]
    apply Iff.intro
    case mp => grind
    case mpr => simp_all; grind
  case box => simp
```
:::

:::definition "Propositional formulas"
A formula is propositional when it has no boxed subformula:
$$`\operatorname{propositional}(A):=\neg\operatorname{containsBox}(A).`

```lean
def L.propositional (A : L) : Bool :=
  !A.containsBox
```
:::

:::definition "Atomic and quasi-atomic formulas"
An atom has the form $`p_n`. A formula is quasi-atomic when it is either atomic or boxed:
$$`\operatorname{quasiAtomic}(A):=
  \operatorname{isAtomic}(A)\lor\operatorname{isBox}(A).`

```lean
@[simp]
def L.isAtomic : L → Bool
  | .atom _ => true
  | _ => false

@[simp]
def L.quasiAtomic (A : L) : Bool :=
  A.isAtomic || A.isBox
```
:::

:::definition "Quasi-atoms"
The type of all quasi-atoms and the finite type of quasi-atomic subformulas of $`A` are
$$`\mathcal L_q:=\{B\in\mathcal L\mid q(B)\},\qquad
S_q(A):=\{B\in S(A)\mid q(B)\}.`

```lean
@[simp]
abbrev Lq : Type := {A : L // A.quasiAtomic}

def Sq (A : L) : Type := {B : L // B.quasiAtomic ∧ B ∈ S A}

instance (A : L) : DecidableEq (Sq A) := Subtype.instDecidableEq

instance (A : L) : Fintype (Sq A) := by
  apply Fintype.ofFinset ((S A).filter (·.quasiAtomic))
  intro x
  simp only [Finset.mem_filter]
  change (x ∈ S A ∧ x.quasiAtomic) ↔ (x.quasiAtomic ∧ x ∈ S A)
  exact and_comm

instance (A : L) : Fintype (Sq A → Bool) := Pi.instFintype
```
:::

:::definition "Auxiliary valuation"
Given $`v:S_q(A)\to\mathbb B`, the value $`V_A^v(B)` for $`B\in S(A)` is defined by
$$`
\begin{aligned}
V_A^v(p_n)&=v(p_n), & V_A^v(\bot)&=\mathsf{false},\\
V_A^v(B\to C)&=V_A^v(B)\Rightarrow V_A^v(C), &
V_A^v(\Box B)&=v(\Box B).
\end{aligned}`

```lean
@[simp]
def V_aux (f1 f2 : L) (v : Sq f1 → Bool) (H : f2 ∈ S f1) : Bool :=
  match H2 : f2 with
  | .atom p => v ⟨.atom p, by simpa⟩
  | ⊥ₜ => false
  | A →ₜ B => V_aux f1 A v (mem_imp_mem H).left → V_aux f1 B v (mem_imp_mem H).right
  | □ₜA => v ⟨□ₜA, by simpa⟩
```
:::

:::definition "Valuation"
The value of $`A` under $`v:S_q(A)\to\mathbb B` is
$$`V^v(A):=V_A^v(A).`

```lean
@[simp]
def V (f1 : L) (v : Sq f1 → Bool) : Bool :=
  V_aux f1 f1 v A_mem_S_A
```
:::

:::definition "Tautology"
A formula is a tautology when every valuation of its quasi-atoms makes it true:
$$`\operatorname{tautology}(A):=\forall v:S_q(A)\to\mathbb B,\ V^v(A)=\mathsf{true}.`

```lean
@[simp]
def L.tautology (A : L) : Bool :=
  ∀ v : Sq A → Bool, V A v
```
:::
