import Mathlib
import VersoManual
import Textbook.Blocks

open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean
open Textbook

set_option pp.rawOnError true

#doc (Manual) "Propositional Modal Logic" =>

# The Language of Propositional Modal Formula

:::definition "Modal formulas"
Let $`Φ` be a denumerable {margin}[`Denumerable` just meaning it has a
one-to-one correspondence with `ℕ`. Mathlib has good built in support for
denumerable types.] set of atomic formulae.
```lean
variable (Φ : Type) [Denumerable Φ]
```
The type of modal formulae is defined inductively,
over atomic formulae, a falsity constant, an implication constructor $`→`,
and a necessity constructor $`\Box` (This presentation is taken from
{citet Goldblatt1992}[]). Using BNF notation, we write the grammar
for formulae as follows where $`p ∈ Φ`:
$$`φ ::= p | ⊥ | φ → φ | □φ`
In lean we define formula as an inducutive type `L Φ`. An inductive type is
a type that is defined by a set of constructors that generate all the elements
of the type. In this case, the constructors are `atom`, `bot`, `imp`, and `box`.
The type of formulae is parameterized by the type of atomic formula $`Φ`.
```lean
--note we ommit the Φ parameter since it is declared as a variable above
inductive L where
| atom : Φ → L
| bot : L
| imp : L → L → L
| box : L → L
deriving Inhabited, Encodable
```
:::

With this type in place we can write formulae in lean using the constructors.
For example, the formula $`□p → q` can be written in lean as
```lean
#check L.imp (L.box (L.atom "p")) (L.atom "q")
```
Note "p" and "q" have the type `String`, which is Denumerable, so we can use
them as atomic formulae.

Writing formulae using the constructors directly as above is cumbersome, we want
to write formulae in lean the same way we write them in the object language.
Lean allows us to define custom notations for types, so we define notations
for the constructors.{margin}[In Lean we will subscript term constructors and
notations with `ₜ` to avoid name clashes with the meta-language (Lean is very
particular with its logical connectives `∧`, `∨`, `¬`, `→`, and `↔` and they do
not support easy overloading) Outside of Lean we will omit the subscript, and
meta-language usage will always be clear from context.]

```lean
notation "⊥ₜ" => L.bot
infixr:30 " →ₜ " => L.imp
prefix:max " □ₜ" => L.box
postfix:max "ᵃ" => L.atom
```

Now we can write the formula $`□p → q` in lean as
```lean
#check □ₜ"p"ᵃ →ₜ "q"ᵃ
```

:::definition "Other Connectives"

At this point, readers familar with modal or even propositional logic will
notice that we are missing some familiar logical connectives. We define the
language to be a minimal *functionally complete*{margin}[meaning that all other
connectives can be defined in terms of this minimal set.] set of connectives.
We define the remaining connectives in terms of the primitive ones.
$$`
\begin{aligned}
¬φ &:= φ → ⊥ \\
⊤ &:= ¬⊥ \\
φ ∧ ψ &:= ¬(φ → ¬ψ) \\
φ ∨ ψ &:= ¬(¬φ ∧ ¬ψ) \\
φ ↔ ψ &:= (φ → ψ) ∧ (ψ → φ)
\end{aligned}
`

```lean
@[simp]
def L.not {Φ : Type} (A : L Φ) : L Φ := A →ₜ ⊥ₜ
prefix:max " ¬ₜ" => L.not

@[simp]
def L.top {Φ : Type} : L Φ := ¬ₜ⊥ₜ
notation "⊤ₜ" => L.top

@[simp]
def L.and {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(A →ₜ ¬ₜB)
infixr:35 " ∧ₜ " => L.and

@[simp]
def L.or {Φ : Type} (A B : L Φ) : L Φ := ¬ₜ(¬ₜA ∧ₜ ¬ₜB)
infixr:30 "∨ₜ " => L.or

@[simp]
def L.iff {Φ : Type} (A B : L Φ) : L Φ := (A →ₜ B) ∧ₜ (B →ₜ A)
infixr:25 " ↔ₜ " => L.iff

@[simp]
def L.dia {Φ : Type} (A : L Φ) : L Φ := ¬ₜ□ₜ¬ₜA
prefix:max "◇ₜ" => L.dia
```
:::

:::definition "Set of Formulae"
The set of all formulae generated by $`Φ` is denoted by $`Fma(Φ)`.
```lean
abbrev Fma : Set (L Φ) := Set.univ
```
:::

:::details "Lean notation and printing support"

For constructive examples we need a concrete type for atomic formulae.
We will use the type of strings as our set of  atomic formulae, that is
$`Φ := String`. This implementation support lets examples use strings directly
as atoms and makes the interpreter print formulae using object-language
notation. To this end we define a `Repr` instance for formulae,
which allows us to print formulae in the lean interpreter.
We also define a coercion from strings to atomic formulae, so that we can
write formulas using strings directly, with an underlying macro to help.
```lean
def L.formatPrec {Φ : Type} [Repr Φ] : L Φ → Nat → Std.Format
  | .atom p, prec => reprPrec p prec
  | .bot, _ => "⊥ₜ"
  | .imp A B, prec =>
    let out := L.formatPrec A 31 ++ " →ₜ " ++ L.formatPrec B 30
    if prec > 30 then Std.Format.bracket "(" out ")" else out
  | .box A, _ => "□ₜ" ++ L.formatPrec A 1024

instance {Φ : Type} [Repr Φ] : Repr (L Φ) where
  reprPrec := L.formatPrec

instance : CoeHTCT String (L String) where
  coe := L.atom

syntax:31 str " →ₜ " term:30 : term
macro_rules
  | `($p:str →ₜ $A:term) => `(L.atom $p →ₜ $A)

syntax:36 str " ∧ₜ " term:35 : term
macro_rules
  | `($p:str ∧ₜ $A:term) => `(L.atom $p ∧ₜ $A)
```
:::
For constructive examples we will use `String` as our set of atomic formulae,
that is $`Φ :=` `String`.

With this we can write the formula $`□(p → q)` as
```lean
#check □ₜ("p" →ₜ "q")
```
Or a more complex formulae such as $`□(p → q) ∧ □(q → r)` as
```lean
#check □ₜ("p" →ₜ "q") ∧ₜ □ₜ("q" →ₜ "r")
```

:::details "Decidable equality Of Formulae"
In order to define things like subformulae we need decidable equality on
formulae. First we have that from the denumberability of $`Φ` we can derive
decidable equality on $`Φ` and $`L Φ`. Decidable equality is a property of a
type that says we have an algorithm to decide whether two elements of said type
are equal or not. We use the `Encodable` typeclass to derive decidable
equality on $`Φ` and $`L Φ`.

```lean
instance : DecidableEq Φ := Encodable.decidableEqOfEncodable Φ
deriving instance DecidableEq, BEq for L
```
With decidable equality in place we have the ability to take unions
and intersections of finite sets of formulae. We will use the `Finset` type to
represent finite sets of formulae. We can also derive a `Repr` instance for
formulae, which allows us to print formulae in the lean interpreter.
:::

# Subformulae, Substitution, and Schemata

:::definition "Subformulae"
The finite set of subformulae of a formula $`A` is defined inductively as:
```lean
@[simp]
def L.subformulae {Φ : Type} [DecidableEq Φ] : L Φ → Finset (L Φ)
| L.atom p => {L.atom p}
| L.bot => {L.bot}
| L.imp A B => {L.imp A B} ∪ L.subformulae A ∪ L.subformulae B
| L.box A => {L.box A} ∪ L.subformulae A
```
We use a prefix S to denote the set of subformulae of a formula, so that $`S[A]`
is the set of all subformulae of $`A`.
```lean
notation "S[" A "]" => L.subformulae A
```

:::

For example the subformulae of $`□(p → q)` are
$`\{□(p → q), p → q, p, q\}`.
```leanEval
#eval S[ □ₜ("p" →ₜ "q") ]
```

:::details "Properties of Subformulae"
A formula is always a subformula of itself.
i.e. membership of subformulae is reflexive.
```lean
@[simp]
theorem L.subformulae_mem_refl (A : L Φ) : A ∈ S[A] := by
  induction A
  case atom p => simp only [L.subformulae, Finset.mem_singleton]
  case bot => simp only [L.subformulae, Finset.mem_singleton]
  case imp A B ihA ihB =>
    simp only [L.subformulae, Finset.singleton_union, Finset.insert_union,
    Finset.mem_insert, Finset.mem_union, true_or]
  case box A ih =>
    simp only [L.subformulae, Finset.singleton_union, Finset.mem_insert,
    true_or]
```
Membership of subformulae is transitive.
```lean
@[simp]
theorem L.subformulae_mem_trans (A B C: L Φ) :
B ∈ S[A] → C ∈ S[B] → C ∈ S[A] := by
  induction A generalizing B C <;> aesop
```

:::

We will often want to discuss Schemata, collections of formulae that share
a common syntactic form. For example "the schema $`□(φ → φ)`" is the collection
of all formulae of the form $`□(φ → φ)` for any formula $`φ`. In set builder
notation we can write this as $`\{□(φ → φ) \mid φ \in Fma(Φ)\}`.

The notion of schema is formalized using uniform substitutions. A uniform
substitution is a function that replaces atomic formulae with arbitrary
formulae. For example the uniform substitution $`σ` defined by $`σ(p) := □p`
and $`σ(q) := q ∨ r` replaces the atomic formula $`p` with $`□p` and
the atomic formula $`q` with $`q ∨ r`. The result of applying this uniform
substitution to the schema $`□(A → A)` is the formula $`□(□p → □p)`.

:::definition "Uniform Substitutions and Substitution Instances"
A uniform substitution is a function $`σ : Φ → Fma(Φ)` that replaces
atomic formulae with arbitrary formulae. The result of applying a uniform
substitution $`σ` to a formula $`φ` is denoted by $`φ /ₛ σ` and is defined
inductively as follows:
```lean
@[simp]
def L.subst {Φ : Type} [DecidableEq Φ] (φ : L Φ) (σ : Φ → L Φ) : L Φ :=
match φ with
| L.atom p => σ p
| L.bot => L.bot
| L.imp φ₁ φ₂ => L.imp (L.subst φ₁ σ) (L.subst φ₂ σ)
| L.box φ₁ => L.box (L.subst φ₁ σ)

infixl:100 "/ₛ" => L.subst
```
Note that this definition is *simultaneous*, meaning that all atomic formulae
are replaced at once, rather than sequentially.

A formula $`φ'` is said to be a substitution instance of a formula $`φ`,
written $`φ' ≼ₛ φ` if it can be obtained by simultaineously substituting
some of the atomic formulae in $`φ` with arbitrary formulae. In otherwords,
$`φ'` is a substitution instance of $`φ` if there exists a uniform substitution
$`σ` such that $`φ' = σ(φ)`.
$$`φ' ≼ₛ φ := ∃ σ, φ' = φ /ₛ σ`
```lean
@[simp]
def L.isSubstInstance {Φ : Type} [DecidableEq Φ] (φ' φ : L Φ) : Prop :=
  ∃ σ : Φ → L Φ, φ' = φ /ₛ σ
infix:50 " ≼ₛ " => L.isSubstInstance
```
:::
With this we can define a schema as the set of all substitution instances
of a formula.
:::definition "Schema"
The schema generated by a formula $`φ` is the set of all substitution instances
of $`φ`, denoted by $`\operatorname{Schema}(φ)`.
```lean

def L.schema {Φ : Type} [DecidableEq Φ] (φ : L Φ) : Set (L Φ) :=
  {φ' | φ' ≼ₛ φ}
notation "[" A "]ₛ" => L.schema A
```
:::

## Properties

```lean

@[simp]
theorem L.mem_schema_iff_is_subst_instance
{Φ : Type} [DecidableEq Φ] {φ' φ : L Φ} :
φ' ∈ [φ]ₛ ↔ φ' ≼ₛ φ := by
  rfl

theorem L.mem_schema_self {Ψ : Type} [DecidableEq Ψ] (φ : L Ψ) :
φ ∈ [φ]ₛ := by
  refine ⟨L.atom, ?_⟩
  induction φ with
  | atom _ => rfl
  | bot => rfl
  | imp φ₁ φ₂ ih₁ ih₂ =>
      exact congrArg₂ L.imp ih₁ ih₂
  | box φ₁ ih =>
      exact congrArg L.box ih

theorem L.subst_instance_of_self {Φ : Type} [DecidableEq Φ] (φ : L Φ) :
φ ≼ₛ φ :=
  L.mem_schema_iff_is_subst_instance.mp (L.mem_schema_self φ)


```

## Decidability of Schema Membership

Membership of a concrete formula in a schema is decidable. i.e., given a formula
$`φ` and a formula $`ψ`, we have an algorithm to decide whether $`ψ` is a
substitution instance of $`φ`. We provide an algorithm for interested readers
and prove soundness and completeness.

The decision procedure traverses $`φ` and $`ψ` together while storing
the formula assigned to each atom of $`φ`. If the same atom occurs again, its
new target must agree with the assignment already stored.
```lean
abbrev L.SubstMap (Φ : Type) := Φ → Option (L Φ)

def L.SubstMap.Extends {Φ : Type} (τ σ : L.SubstMap Φ) : Prop :=
  ∀ p B, σ p = some B → τ p = some B

def L.SubstMap.Agrees {Φ : Type}
    (τ : L.SubstMap Φ) (σ : Φ → L Φ) : Prop :=
  ∀ p B, τ p = some B → σ p = B

def L.matchSubst {Φ : Type} [DecidableEq Φ] :
    L Φ → L Φ → L.SubstMap Φ → Option (L.SubstMap Φ)
  | .atom p, B, τ =>
      match τ p with
      | some C => if C = B then some τ else none
      | none => some fun q => if q = p then some B else τ q
  | .bot, .bot, τ => some τ
  | .imp A₁ A₂, .imp B₁ B₂, τ => do
      let τ ← L.matchSubst A₁ B₁ τ
      L.matchSubst A₂ B₂ τ
  | .box A, .box B, τ => L.matchSubst A B τ
  | _, _, _ => none
```

The matcher never changes an assignment that it has already made.

```lean
theorem L.matchSubst_extends {Φ : Type} [DecidableEq Φ]
    {A B : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst A B τ = some τ') : τ'.Extends τ := by
  induction A generalizing B τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h <;> simp_all [L.SubstMap.Extends]
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        intro q C hq
        by_cases heq : q = p
        · simp only [heq, if_pos]
          subst q
          simp_all
        · simp [heq, hq]
  | bot =>
      cases B <;> simp_all [L.matchSubst, L.SubstMap.Extends]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases B with
      | imp B₁ B₂ =>
          cases h₁ : L.matchSubst A₁ B₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            intro p C hp
            exact ih₂ h p C (ih₁ h₁ p C hp)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases B <;> simp_all [L.matchSubst]
      exact ih h
```

The next two results prove that matching is sound and complete with respect
to uniform substitution.

```lean
theorem L.matchSubst_sound {Φ : Type} [DecidableEq Φ]
    {φ ψ : L Φ} {τ τ' : L.SubstMap Φ}
    (h : L.matchSubst φ ψ τ = some τ') {σ : Φ → L Φ}
    (hagrees : τ'.Agrees σ) : φ /ₛ σ = ψ := by
  induction φ generalizing ψ τ τ' with
  | atom p =>
      simp only [L.matchSubst] at h
      split at h
      · rename_i C hC
        split at h
        · rename_i heq
          simp_all [L.SubstMap.Agrees, L.subst]
        · simp_all
      · rename_i hnone
        simp only [Option.some.injEq] at h
        subst τ'
        simp only [L.subst]
        apply hagrees p ψ
        simp
  | bot => cases ψ <;> simp_all [L.matchSubst, L.subst]
  | imp A₁ A₂ ih₁ ih₂ =>
      cases ψ with
      | imp ψ₁ ψ₂ =>
          cases h₁ : L.matchSubst A₁ ψ₁ τ with
          | some τ₁ =>
            simp only [L.matchSubst, h₁] at h
            have hext := L.matchSubst_extends h
            have hagrees₁ : τ₁.Agrees σ := fun p C hp =>
              hagrees p C (hext p C hp)
            exact congrArg₂ L.imp
              (ih₁ h₁ hagrees₁) (ih₂ h hagrees)
          | none => simp [L.matchSubst, h₁] at h
      | _ => simp_all [L.matchSubst]
  | box A ih =>
      cases ψ with
      | box ψ => exact congrArg L.box (ih h hagrees)
      | _ => simp_all [L.matchSubst]

theorem L.matchSubst_complete {Φ : Type} [DecidableEq Φ]
{φ ψ : L Φ} {τ : L.SubstMap Φ} {σ : Φ → L Φ}
(hagrees : τ.Agrees σ) (hsubst : φ /ₛ σ = ψ) :
∃ τ', L.matchSubst φ ψ τ = some τ' ∧ τ'.Agrees σ := by
  induction φ generalizing ψ τ with
  | atom p =>
      simp only [L.subst] at hsubst
      subst ψ
      simp only [L.matchSubst]
      split
      · rename_i C hC
        have hσ := hagrees p C hC
        subst C
        simp [hagrees]
      · rename_i hnone
        refine ⟨fun q => if q = p then some (σ p) else τ q, ?_, ?_⟩
        · simp
        · intro q C hq
          simp only at hq
          split at hq
          · simp_all
          · exact hagrees q C hq
  | bot =>
      simp only [L.subst] at hsubst
      subst ψ
      exact ⟨τ, rfl, hagrees⟩
  | imp A₁ A₂ ih₁ ih₂ =>
      cases ψ with
      | imp ψ₁ ψ₂ =>
          simp only [L.subst, L.imp.injEq] at hsubst
          obtain ⟨τ₁, h₁, hagrees₁⟩ := ih₁ hagrees hsubst.1
          obtain ⟨τ₂, h₂, hagrees₂⟩ := ih₂ hagrees₁ hsubst.2
          exact ⟨τ₂, by simp [L.matchSubst, h₁, h₂], hagrees₂⟩
      | _ => simp_all [L.subst]
  | box A ih =>
      cases ψ with
      | box ψ =>
          simp only [L.subst, L.box.injEq] at hsubst
          obtain ⟨τ', h, hagrees'⟩ := ih hagrees hsubst
          exact ⟨τ', h, hagrees'⟩
      | _ => simp_all [L.subst]
```

Starting the matcher with an empty partial substitution therefore decides
whether $`A'` is a substitution instance of $`A`.

```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
Decidable (A' ≼ₛ A) := by
  let empty : L.SubstMap Φ := fun _ => none
  match h : L.matchSubst A A' empty with
  | some τ =>
      apply isTrue
      let σ : Φ → L Φ := fun p => (τ p).getD (.atom p)
      refine ⟨σ, ?_⟩
      symm
      apply L.matchSubst_sound h
      intro p B hp
      simp [σ, hp]
  | none =>
      apply isFalse
      rintro ⟨σ, hσ⟩
      have hagrees : empty.Agrees σ := by
        simp [empty, L.SubstMap.Agrees]
      obtain ⟨τ, hτ, _⟩ :=
        L.matchSubst_complete hagrees hσ.symm
      simp_all
```

For example, replacing $`p` uniformly by $`q` succeeds, whereas replacing its
two occurrences by different formulae does not.

```leanEval
#eval decide (("q" →ₜ "q") ≼ₛ ("p" →ₜ "p"))
#eval decide (("q" →ₜ "r") ≼ₛ ("p" →ₜ "p"))
```

We thus have membership in a schema is decidable, since $`A'` is a
substitution instance of $`A` if and only if the matcher succeeds.
```lean
instance {Φ : Type} [DecidableEq Φ] (A' A : L Φ) :
    Decidable (A' ∈ [A]ₛ) := by
  change Decidable (A' ≼ₛ A)
  infer_instance
```

For example, the formula $`□(p → q)` is a substitution instance of the schema
$`□(A → B)` by substituting $`p` for $`A` and $`q` for $`B`.
```leanEval
#eval (□ₜ("p" →ₜ "q") ∈ [□ₜ("A" →ₜ "B")]ₛ)
```
A more complex example is that the formula $`□(p → (q ∧ r)) ∧ □(p → ¬(q ∧ r))`
is a substitution instance of the schema $`□(A → B) ∧ □(A → ¬B)` by
substituting $`p` for $`A` and $`q ∧ r` for $`B`.
```leanEval
#eval ((□ₜ("p" →ₜ ("q" ∧ₜ "r")) ∧ₜ □ₜ("p" →ₜ ¬ₜ("q" ∧ₜ "r")))
  ∈ [□ₜ("A" →ₜ "B") ∧ₜ □ₜ("A" →ₜ ¬ₜ"B")]ₛ)
```

# Tautologies

An important class of formulae are tautologies, formulae that are true under
every valuation of their atomic propositions. In propositional logic,
defining tautologies is straightforward, as we are just dealing with valuations
on atomic propositions. In modal logic, however, we have to deal with the
additional complexity of the box operator. We follow {citet Goldblatt1992}[]
and define tautologies in terms of _quasi-atomic subformulae_, by treating
boxed formulae as a kind of atomic proposition. This allows us to define
tautologies in a way analogous to propositional logic.

:::definition "Quasi-atomic Formulae"
A formula is quasi-atomic if it is either atomic or begins with a box.
```lean
@[simp]
def L.isQuasiAtomic {Φ : Type} : L Φ → Prop
| .atom _ => True
| .box _ => True
| _ => False

--We have an algorithem for deciding whether a formula is quasi-atomic.
instance {Φ : Type} [DecidableEq Φ] (φ : L Φ) :
Decidable (φ.isQuasiAtomic) := by
  cases φ <;> simp only [L.isQuasiAtomic] <;> infer_instance
```
:::

Some examples of quasi-atomic formulae are $`p`, $`□p`, and $`□(p → q)`. Some
examples of formulae that are not quasi-atomic are $`p → q`, $`□p → q`, and
$`□(p → q) → r`.
```leanEval
#eval "p"ᵃ.isQuasiAtomic --true
#eval (□ₜ "p"ᵃ).isQuasiAtomic --true
#eval (□ₜ("p"ᵃ →ₜ "q"ᵃ)).isQuasiAtomic --true
#eval ("p" →ₜ "q").isQuasiAtomic --false
#eval (□ₜ "p"ᵃ →ₜ "q"ᵃ ).isQuasiAtomic --false
#eval (□ₜ("p"ᵃ →ₜ "q"ᵃ) →ₜ "r"ᵃ).isQuasiAtomic --false
```

:::definition "Quasi-atomic Subformulae Valuations"
A Quasi-atomic subformula valuation is a valuation function that assigns
true or false to each quasi-atomic subformula of a formula.

```lean
abbrev QuasiAtomicSubformulaValuation {Φ : Type} [DecidableEq Φ] (φ : L Φ) :=
  (ψ : L Φ) → ψ.isQuasiAtomic → ψ ∈ S[φ] → Prop

```
Given a quasi-atomic valuation `V`, we can extend it to a valuation of
an arbitrary formula `φ`. To do this, we need to be able to lift
valuations on implications to valuations on their left and right subformulae.
The following definitions provide this lifting.
```lean
/--
Given a quasi-atomic subformula valuation of an implication,
return a valuation over subformulae of the left-hand side of the implication.
 -/
def QuasiAtomicSubformulaValuation.left {Φ : Type} [DecidableEq Φ]
{φ ψ : L Φ} (V : QuasiAtomicSubformulaValuation (φ →ₜ ψ)) :
QuasiAtomicSubformulaValuation φ :=
  fun χ hqa hχ => V χ hqa (by
    simp only [L.subformulae, Finset.mem_union,
      Finset.mem_singleton]
    exact Or.inl (Or.inr hχ))

def QuasiAtomicSubformulaValuation.right {Φ : Type} [DecidableEq Φ]
{φ ψ : L Φ}
(V : QuasiAtomicSubformulaValuation (φ →ₜ ψ)) :
QuasiAtomicSubformulaValuation ψ :=
  fun χ hqa hχ => V χ hqa (by
    simp only [L.subformulae, Finset.mem_union,
      Finset.mem_singleton]
    exact Or.inr hχ)
```
With these we can then lift the valuation of quasi-atomic subformulae
to a valuation of entire formula. We write this using the notation $`⟦φ⟧_v`
where V is a quasi-atomic subformula valuation.
```lean
@[simp]
def LiftedQuasiAtomicValuation {Φ : Type} [DecidableEq Φ]
 (φ : L Φ) (V : QuasiAtomicSubformulaValuation φ) : Prop :=
match h: φ with
| .atom p => V (.atom p)
  (by simp only [L.isQuasiAtomic])
  (by simp only [L.subformulae, Finset.mem_singleton])
| .box φ => V (.box φ)
  (by simp only [L.isQuasiAtomic])
  (by subst h ; simp_all only [L.subformulae,
   Finset.singleton_union, Finset.mem_insert, true_or])
| .bot => False
| .imp φ ψ =>
  (LiftedQuasiAtomicValuation φ V.left) → (LiftedQuasiAtomicValuation ψ V.right)

notation "⟦" φ "⟧" V => LiftedQuasiAtomicValuation φ V

```
:::

:::definition "Tautologies"
We define the notion of tautology in terms of quasi-atomic subformulae.
We say a formula φ is a tautology if its lifted valuation is true for
every valuation of its quasi-atomic subformula. This idea naturally
coresponds to the notion of tautology in propositional logic, where a formula
is a tautology if it is true under every assignment of truth values to
its propositional variables, except now we consider quasi-atomic subformulae
instead.
```lean
@[simp]
def L.isTautology {Φ : Type} [DecidableEq Φ] (φ : L Φ) : Prop :=
  ∀ V : QuasiAtomicSubformulaValuation φ, ⟦φ⟧ V
prefix:max "⊢ₜ " => L.isTautology
```
:::

## Properties of Tautologies and Quasi-atomic Formulae

::: theorem "Congruence of Lifted Quasi-Atomic Valuations"
If two quasi-atomic subformula valuations $`V` and $`W` agree on all
quasi-atomic subformulae  of a formula φ, then their lifted valuations
are equivalent.
$$`⟦φ⟧_V ↔ ⟦φ⟧_W`$$
```lean
lemma LiftedQuasiAtomicValuation.congr
(φ : L Φ) (V W : QuasiAtomicSubformulaValuation φ)
(H : ∀ B hqa hB hB', V B hqa hB = W B hqa hB') :
((⟦φ⟧ V) ↔ (⟦φ⟧ W)) := by
  induction φ with
  | atom p => exact iff_of_eq (by apply_assumption)
  | bot => simp only [LiftedQuasiAtomicValuation]
  | box A => exact iff_of_eq (by apply_assumption)
  | imp A B ihA ihB =>
    simp only [LiftedQuasiAtomicValuation]
    rw [ihA V.left W.left, ihB V.right W.right]
    all_goals intros;
    exact H _ _ _ _
    exact H _ _ _ _
```
:::

One class of formulae that will be particularly important for us are the
"box-free" formulae, formulae that do not contain any boxed subformulae, i.e.
formulae that are purely propositional.

::: definition "Box-Free Formulae and Propositional Tautologies"
A formula is box-free if it does not contain any boxed subformulae.
```lean
@[simp]
def L.boxFree {Φ : Type} : L Φ → Prop
| .atom _ => True
| .bot => True
| .imp φ ψ => φ.boxFree ∧ ψ.boxFree
| .box _ => False

@[simp]
def L.isPropTautology {Φ : Type} [DecidableEq Φ] (φ : L Φ) : Prop :=
  (⊢ₜ φ) ∧ φ.boxFree
prefix:max "⊢ₚ " => L.isPropTautology
```
:::

From this we can show the following important result,
that any tautology is a substitution instance of a box-free tautology.

::: theorem "Box-Free Tautologies"

Any tautology is a subsitution instance of
a "box-free" tautology, i.e. a tautology in propositional logic.

_Proof._ The proof replaces every quasi-atomic part of $`φ`—each atom and each boxed
subformula—by a fresh atomic name. Because $`Φ` is denumerable, formulae can be
encoded injectively as elements of $`Φ`; preserving $`⊥` and $`→` then produces
a box-free formula $`ψ`.

Every valuation of the new atoms in $`ψ` determines a valuation of the
corresponding quasi-atoms in $`φ`. A structural induction shows that $`ψ` and
$`φ` have the same truth value under these corresponding valuations, so the
tautologicity of $`φ` implies that of $`ψ`. Finally, substituting each fresh
name by the quasi-atomic formula it encodes reconstructs $`φ`, making $`φ` a
substitution instance of $`ψ`.
```lean
theorem L.subst_boxFree_tautology {Φ : Type} [Denumerable Φ]
(φ : L Φ) (hφ : ⊢ₜ φ) :
∃ (ψ : L Φ), (⊢ₚ ψ) ∧ φ ≼ₛ ψ := by
  classical
  let name (A : L Φ) := Denumerable.ofNat Φ (Encodable.encode A)
  let erase : L Φ → L Φ := L.rec
    (fun p => .atom (name (.atom p))) .bot
    (fun _ _ A B => A →ₜ B)
    (fun A _ => .atom (name (.box A)))
  let eval : L Φ → (L Φ → Prop) → Prop := L.rec
    (fun p V => V (.atom p)) (fun _ => False)
    (fun _ _ VA VB V => VA V → VB V)
    (fun A _ V => V (.box A))
  have total : ∀ (A : L Φ) (V : L Φ → Prop),
      LiftedQuasiAtomicValuation A (fun B _ _ => V B) ↔ eval A V := by
    intro A; induction A with
    | atom p => intro V; rfl
    | bot => intro V; rfl
    | box A => intro V; rfl
    | imp A B ihA ihB =>
        intro V
        simp only [LiftedQuasiAtomicValuation, eval]
        rw [LiftedQuasiAtomicValuation.congr (Φ := Φ) A _
            (fun C _ _ => V C),
          LiftedQuasiAtomicValuation.congr (Φ := Φ) B _
            (fun C _ _ => V C), ihA, ihB]
        all_goals intros; rfl
  have free : ∀ A, (erase A).boxFree := by
    intro A; induction A <;> simp_all [erase]
  have rename : ∀ A V, eval (erase A) V ↔
      eval A (fun B => V (.atom (name B))) := by
    intro A; induction A <;> simp_all [erase, eval]
  have subst : ∀ A, A = L.subst (erase A)
    (fun p => (Encodable.decode (Encodable.encode p)).getD (L.atom p)) := by
    intro A; induction A with
    | atom p =>
        simp [erase, name, L.subst, Denumerable.encode_ofNat]
    | bot => rfl
    | imp A B ihA ihB =>
        simp only [erase, L.subst, L.imp.injEq]
        exact ⟨ihA, ihB⟩
    | box A =>
        simp [erase, name, L.subst, Denumerable.encode_ofNat]
  refine ⟨erase φ, ⟨?_, free φ⟩, ⟨_, subst φ⟩⟩
  · intro W
    let V : L Φ → Prop := fun A =>
      if hqa : A.isQuasiAtomic then
        if hA : A ∈ (erase φ).subformulae then W A hqa hA
        else False
      else False
    rw [LiftedQuasiAtomicValuation.congr
      (Φ := Φ) _ W (fun A _ _ => V A)]
    · rw [total, rename, ← total]
      exact hφ (fun A _ _ => V (.atom (name A)))
    · intro A hqa hA hA'
      simp only [V, dif_pos hqa, dif_pos hA]
```

:::

# Frames and Models

:::definition "Frames and Models"

A frame is a pair $`(S, R)` where `S` is a non-empty set of worlds and $R$ is
a binary relation on $`S` called the accessibility relation.

```lean
structure Frame where
  -- The type of worlds
  S : Type
  /-- Require that the set of worlds is non-empty -/
  [S_nonempty : Nonempty S]
  /-- The accessibility relation on worlds -/
  R : S → S → Prop
```

A Φ-model is a pair $`(F, V)` where `F` is a frame and `V` is a _valuation
function_ that assigns worlds and propositional variables to truth values.
I.e a propositional variable $`p` holds at a world $`w` if and only if
$`V(p,w)`$.

In Lean we represent models as an extension of frames with a valuation function.
{margin}[This lets us use `M.S` and `M.R` from the frame, rather than needing to
write `M.F.S` and `M.F.R`, if we used the frame directly in the structure.]
```lean
variable {Φ : Type}

structure Model extends Frame where
  V : Φ → S → Prop

```

```lean -show

--The following code is used to render finite models as diagrams.
--It is not part of the formalization, but extremely useful for visualization.
open Illuminate

private def decideToBool (d : Decidable p) : Bool :=
  match d with
  | .isTrue _ => true
  | .isFalse _ => false

private def subscriptDigit : Char → Char
  | '0' => '₀' | '1' => '₁' | '2' => '₂' | '3' => '₃' | '4' => '₄'
  | '5' => '₅' | '6' => '₆' | '7' => '₇' | '8' => '₈' | '9' => '₉'
  | c => c

private def worldLabel (i : Nat) : String :=
  "w" ++ String.ofList ((toString i).toList.map subscriptDigit)

/-- Automatically render a finite model. -/
def Model.diagram (M : @Model Φ) [FinEnum M.S] [Denumerable Φ]
    [decideR : DecidableRel M.R]
    [decideV : ∀ p w, Decidable (M.V p w)] : Diagram SVG :=
  let cfg : StateDiagramConfig :=
    { radius := 24, spacing := 100 }
  let worlds := FinEnum.toList M.S
  let atoms : List (Φ × String) :=
    [(Denumerable.ofNat Φ 0, "φ"),
      (Denumerable.ofNat Φ 1, "ψ"),
      (Denumerable.ofNat Φ 2, "χ")]
  let nodes := worlds.zipIdx.map fun (w, i) =>
    let trueAtoms := atoms.filterMap fun (p, label) =>
      if decideToBool (decideV p w) then
        some label
      else none
    let valuation :=
      if trueAtoms.isEmpty then "∅"
      else ", ".intercalate trueAtoms
    cfg.state i s!"{worldLabel i}\n{valuation}"
  let edges := worlds.zipIdx.flatMap fun (w, i) =>
    worlds.zipIdx.filterMap fun (v, j) =>
      if decideToBool (decideR w v) then
        if i = j then some (cfg.loop i "")
        else if j = i + 1 then some (cfg.edge i j "")
        else if i < j then some (cfg.arc i j "" 60)
        else some (cfg.arc i j "" (-45))
      else none
  overlay (nodes ++ edges)
```
:::

:::definition "Satisfaction in a Model"
Let $`M = (S, R, V)` be a Φ-model and let $`w` be a world in `S`.
We define the satisfaction relation $`M \vDash_w φ` for a formula `φ`
inductively as follows.
$$`
\begin{aligned}
M \vDash_w p &\quad\text{iff}\quad V(p, w)\\
M \vDash_w ⊥ &\quad\text{iff}\quad \text{False}\\
M \vDash_w φ → ψ &\quad\text{iff}\quad M \vDash_w φ \rightarrow M \vDash_w ψ\\
M \vDash_w □φ &\quad\text{iff}\quad \forall v, R(w, v) \rightarrow M \vDash_v φ
\end{aligned}
`

```lean
@[simp]
def Model.satisfies (M : @Model Φ) (w : M.S) : L Φ → Prop
| .atom p => M.V p w
| ⊥ₜ       => False
| φ →ₜ ψ   => M.satisfies w φ → M.satisfies w ψ
| □ₜφ      => ∀ v : M.S, M.R w v → M.satisfies v φ

notation M " ⊨[" w "] " φ => Model.satisfies M w φ
notation M " ⊭[" w "] " φ => ¬ M ⊨[w] φ

```
Thus `M ⊨[w] φ` says that `φ` is satisfied at `w`, while
`M ⊭[w] φ` says that it is not satisfied there.

Satisfaction extends to the other logical connectives based on their
definitions. Note that these themselves are not definitions, but are theorems
that follow from the definition of satisfaction and the definitions of the
logical connectives.
$$`
\begin{aligned}
M \vDash_w ¬φ &\quad\text{iff}\quad M \nvDash_w φ\\
M \vDash_w φ ∧ ψ &\quad\text{iff}\quad M \vDash_w φ \wedge M \vDash_w ψ\\
M \vDash_w φ ∨ ψ &\quad\text{iff}\quad M \vDash_w φ \vee M \vDash_w ψ\\
M \vDash_w φ ↔ ψ &\quad\text{iff}\quad M \vDash_w φ \leftrightarrow M \vDash_w ψ\\
M \vDash_w ◇φ &\quad\text{iff}\quad \exists v, R(w, v) \wedge M \vDash_v φ
\end{aligned}
`

```lean
theorem Model.satisfies_neg (M : @Model Φ) (w : M.S) (φ : L Φ) :
(M ⊨[w] ¬ₜφ) ↔ (M ⊭[w] φ) := by
  rfl

@[simp]
theorem Model.satisfies_and (M : @Model Φ) (w : M.S) (φ ψ : L Φ) :
(M ⊨[w] (φ ∧ₜ ψ)) ↔ (M ⊨[w] φ) ∧ (M ⊨[w] ψ) := by
  simp only [L.and, L.not, Model.satisfies, imp_false,
    Classical.not_imp, not_not]

@[simp]
theorem Model.satisfies_or (M : @Model Φ) (w : M.S) (φ ψ : L Φ) :
(M ⊨[w] (φ ∨ₜ ψ)) ↔ (M ⊨[w] φ) ∨ (M ⊨[w] ψ) := by
  simp only [L.or, L.and, L.not, Model.satisfies,
    imp_false, Classical.not_imp, not_not]
  tauto

@[simp]
theorem Model.satisfies_iff (M : @Model Φ) (w : M.S) (φ ψ : L Φ) :
(M ⊨[w] (φ ↔ₜ ψ)) ↔ ((M ⊨[w] φ) ↔ (M ⊨[w] ψ)) := by
  simp only [L.iff, Model.satisfies_and, Model.satisfies]
  apply Iff.intro <;> grind only [cases Or]

@[simp]
theorem Model.satisfies_dia (M : @Model Φ) (w : M.S) (φ : L Φ) :
(M ⊨[w] (◇ₜ φ)) ↔ ∃ v : M.S, M.R w v ∧ (M ⊨[v] φ) := by
  classical
  simp only [L.dia, L.not, Model.satisfies]
  apply Iff.intro
  · intro h
    by_contra hnone
    apply h
    intro v hv hφ
    apply hnone
    exact ⟨v, hv, hφ⟩
  · intro h hbox
    rcases h with ⟨v, hv, hφ⟩
    exact hbox v hv hφ
```
:::

:::definition "Truth and Validity"

A formula φ is true in a model M if it is satisfied at every world in M.
$$`M \vDash^m φ \quad\text{iff}\quad \forall w, M \vDash_w φ`

We use superscripts on the turnstile to make the level of the
semantics explicit: `m` for models, `f` for frames, and `c` for
classes of frames. Replacing `⊨` with `⊭` negates each relation.

```lean
@[simp]
def L.true_in_model (M : @Model Φ) (φ : L Φ) : Prop :=
  ∀ w, M ⊨[w] φ

infixl:51 " ⊨ᵐ " => L.true_in_model
notation M " ⊭ᵐ " φ => ¬ L.true_in_model M φ
```

A formula φ is valid in a frame F if it is true in every model based on F.
$$`F \vDash^f φ := ∀ V, (F, V) \vDash^m φ`
```lean
@[simp]
def L.valid_in_frame (F : Frame) (φ : L Φ) : Prop :=
  ∀ V, (Model.mk F V) ⊨ᵐ φ

infixl:51 " ⊨ᶠ " => L.valid_in_frame
notation F " ⊭ᶠ " φ => ¬ L.valid_in_frame F φ
```

A formula φ is valid in a class of frames C if it is valid in every frame in C.
$$`C \vDash^c φ := ∀ F ∈ C, F \vDash^f φ`
In Lean we represent a class as a set of frames.
```lean
@[simp]
def L.valid_in_class (C : Set Frame) (φ : L Φ) : Prop :=
  ∀ F : Frame, F ∈ C → F ⊨ᶠ φ

infixl:51 " ⊨ᶜ " => L.valid_in_class
notation C " ⊭ᶜ " φ => ¬ L.valid_in_class C φ
```

We say a formula *is valid* if it is true in all models,
or equivalently, valid in the class of all frames.
```lean
@[simp]
def L.valid (φ : L Φ) : Prop :=
  ∀ M : @Model Φ, M ⊨ᵐ φ
prefix:max "⊨ " => L.valid
notation "⊭ " φ => ¬ L.valid φ

theorem L.valid_iff_valid_in_class (φ : L Φ) :
(⊨ φ) ↔ Set.univ ⊨ᶜ φ := by
  simp only [valid, true_in_model, valid_in_class,
    Set.mem_univ, valid_in_frame, forall_const]
  apply Iff.intro
  · intro a F V w
    simp_all only
  · intro a M w
    simp_all only
```


We have analogous definitions for truth and validity over schemas.
A schema is true in a model if every instance of the schema is
true in the model. We define these such that the
`[]ₛ` notation is implicity when using the `⊨ˢ` notations.

```lean
@[simp]
def Schema.true_in_model [DecidableEq Φ] (Γ : L Φ) (M : @Model Φ) : Prop :=
  ∀ φ ∈ [Γ]ₛ, M ⊨ᵐ φ
notation M " ⊨ᵐˢ " Γ => Schema.true_in_model Γ M
notation M " ⊭ᵐˢ " Γ => ¬ Schema.true_in_model Γ M

@[simp]
def Schema.valid_in_frame [DecidableEq Φ] (Γ : L Φ) (F : Frame) : Prop :=
  ∀ M : @Model Φ, M.toFrame = F → M ⊨ᵐˢ Γ
notation F " ⊨ᶠˢ " Γ => Schema.valid_in_frame Γ F
notation F " ⊭ᶠˢ " Γ => ¬ Schema.valid_in_frame Γ F

@[simp]
def Schema.valid_in_class [DecidableEq Φ] (Γ : L Φ) (C : Set Frame) : Prop :=
  ∀ F : Frame, F ∈ C → F ⊨ᶠˢ Γ
notation C " ⊨ᶜˢ " Γ => Schema.valid_in_class Γ C
notation C " ⊭ᶜˢ " Γ => ¬ Schema.valid_in_class Γ C

@[simp]
def Schema.valid [DecidableEq Φ] (Γ : L Φ) : Prop :=
  ∀ M : @Model Φ, M ⊨ᵐˢ Γ
prefix:max "⊨ˢ " => Schema.valid
notation "⊭ˢ " Γ => ¬ Schema.valid Γ

```
:::


We can show a formula is not valid by providing a countermodel, i.e. a model
in which the formula is not true. Similarly we can show a schema is not
valid by providing a countermodel in which some instance of the schema
is not true, or by directly providing a countermodel and a counterinstance
of the schema.
```lean
@[simp]
theorem not_valid_iff_countermodel {φ : L Φ} :
(⊭ φ) ↔ ∃ M : @Model Φ, M ⊭ᵐ φ := by
  simp only [L.valid, L.true_in_model, not_forall]

@[simp]
theorem schema_not_valid_iff_countermodel [DecidableEq Φ] {Γ : L Φ} :
(⊭ˢ Γ) ↔ ∃ M : @Model Φ, M ⊭ᵐˢ Γ := by
  simp only [Schema.valid, Schema.true_in_model, not_forall]

@[simp]
theorem schema_not_valid_iff_countermodel_and_counterinstance
[DecidableEq Φ] {Γ : L Φ} :
(⊭ˢ Γ) ↔ ∃ M : @Model Φ, ∃ φ ∈ [Γ]ₛ, M ⊭ᵐ φ := by
  simp

theorem schema_not_valid_of_not_valid
[DecidableEq Φ] {Γ : L Φ} (h : ⊭ Γ) : ⊭ˢ Γ := by
  apply schema_not_valid_iff_countermodel_and_counterinstance.mpr
  rcases not_valid_iff_countermodel.mp h with ⟨M, hM⟩
  exact ⟨M, Γ, L.mem_schema_self Γ, hM⟩
```

## Properties

The lifted quasi-atomic valuation induced by truth at a world agrees
with satisfaction at that world. More generally, any quasi-atomic
valuation assigning those same truth values agrees with satisfaction.


## Exercises

1) Show that the following schema are true in all models.
$$`
\begin{aligned}
□⊤ & \\
□(φ → ψ) → (□φ → □ψ) & \text{(the K axiom)} \\
◇(φ → ψ) → (□φ → ◇ψ) & \\
□(φ → ψ) → (◇φ → ◇ψ) & \\
□(φ ∧ ψ) ↔ (□φ ∧ □ψ) & \\
◇(φ ∨ ψ) ↔ (◇φ ∨ ◇ψ) & \\
\end{aligned}`

:::details "Solutions"
The denumerability of `Φ` gives us an enumeration of its atoms.
We call its first two atoms `φ` and `ψ`. After choosing an arbitrary
instance of a schema, its substitution `σ` turns these placeholders
into arbitrary formulas.

```lean
section Examples

variable [Denumerable Φ]

local notation "φ₀" => Denumerable.ofNat Φ 0
local notation "ψ₀" => Denumerable.ofNat Φ 1
scoped[ExampleFormulas] notation "φ" => L.atom φ₀
scoped[ExampleFormulas] notation "ψ" => L.atom ψ₀

example : ⊨ˢ (□ₜ⊤ₜ : L Φ) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  intro w v _ h2
  exact h2

open scoped ExampleFormulas in
example : ⊨ˢ (□ₜ(φ →ₜ ψ) →ₜ (□ₜφ →ₜ □ₜψ)) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  intro w hbox hφ v hv
  exact hbox v hv (hφ v hv)

open scoped ExampleFormulas in
example : ⊨ˢ (◇ₜ(φ →ₜ ψ) →ₜ (□ₜφ →ₜ ◇ₜψ)) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  intro w hdia hbox
  rcases (M.satisfies_dia w _).mp hdia with ⟨v, hv, himp⟩
  exact (M.satisfies_dia w _).mpr ⟨v, hv, himp (hbox v hv)⟩

open scoped ExampleFormulas in
example : ⊨ˢ (□ₜ(φ →ₜ ψ) →ₜ (◇ₜφ →ₜ ◇ₜψ)) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  intro w hbox hdia
  rcases (M.satisfies_dia w _).mp hdia with ⟨v, hv, hφ⟩
  exact (M.satisfies_dia w _).mpr ⟨v, hv, hbox v hv hφ⟩

open scoped ExampleFormulas in
example : ⊨ˢ (□ₜ(φ ∧ₜ ψ) ↔ₜ (□ₜφ ∧ₜ □ₜψ)) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  change M ⊨ᵐ (□ₜ(σ φ₀ ∧ₜ σ ψ₀) ↔ₜ (□ₜ(σ φ₀) ∧ₜ □ₜ(σ ψ₀)))
  intro w
  rw [Model.satisfies_iff, Model.satisfies_and]
  constructor
  · intro h
    constructor
    · intro v hv
      exact (M.satisfies_and v _ _).mp (h v hv) |>.left
    · intro v hv
      exact (M.satisfies_and v _ _).mp (h v hv) |>.right
  · intro h v hv
    exact (M.satisfies_and v _ _).mpr
      ⟨h.left v hv, h.right v hv⟩

open scoped ExampleFormulas in
example : ⊨ˢ (◇ₜ(φ ∨ₜ ψ) ↔ₜ (◇ₜφ ∨ₜ ◇ₜψ)) := by
  intro M χ hχ
  rcases hχ with ⟨σ, rfl⟩
  change M ⊨ᵐ (◇ₜ(σ φ₀ ∨ₜ σ ψ₀) ↔ₜ (◇ₜ(σ φ₀) ∨ₜ ◇ₜ(σ ψ₀)))
  intro w
  rw [Model.satisfies_iff, Model.satisfies_or]
  apply Iff.intro
  · case mp =>
    intro h
    rcases (M.satisfies_dia w _).mp h with ⟨v, hv, hφψ⟩
    cases (M.satisfies_or v _ _).mp hφψ with
    | inl hφ =>
        exact Or.inl ((M.satisfies_dia w _).mpr
          ⟨v, hv, hφ⟩)
    | inr hψ =>
        exact Or.inr ((M.satisfies_dia w _).mpr
          ⟨v, hv, hψ⟩)
  · case mpr =>
    intro h
    cases h with
    | inl hφ =>
      rcases (M.satisfies_dia w _).mp hφ with
        ⟨v, hv, hφv⟩
      exact (M.satisfies_dia w _).mpr
        ⟨v, hv, (M.satisfies_or v _ _).mpr (Or.inl hφv)⟩
    | inr hψ =>
      rcases (M.satisfies_dia w _).mp hψ with
        ⟨v, hv, hψv⟩
      exact (M.satisfies_dia w _).mpr
        ⟨v, hv, (M.satisfies_or v _ _).mpr (Or.inr hψv)⟩
```
:::

2) Show that the following schema do not hold in all frames by
providing a countermodel or counterframe. Some of these formulae are famous
named axioms, which we will study in later chapters.
$$`
\begin{aligned}
□φ → φ & \text{(the T axiom)} \\
◇⊤ & \text{(variant of the D axiom)} \\
□(φ → ψ) → (□φ → ◇ψ) & \\
◇φ → □φ & \text{(Brouwer's axiom / the 5 axiom)} \\
□(□φ → ψ) ∨ □(□ψ → □φ) &  \\
□(φ ∨ ψ) → (□φ ∨ □ψ) & \\
□(□φ → φ) → □φ & \text{(Löb's axiom)}
\end{aligned}`

:::details "Solutions"
In each picture, an arrow from wᵢ to wⱼ means that wⱼ is accessible from wᵢ.The
second line inside each circle lists which of φ, ψ, and χ are true there;
∅ means that none of these atoms is true.

The denumerability of Φ ensures that φ and ψ name distinct atoms.

```lean
theorem schema_atoms_ne : φ₀ ≠ ψ₀ := by
  intro h
  have h' := congrArg (Encodable.encode : Φ → Nat) h
  simpa [Denumerable.encode_ofNat] using h'
```

For $`□φ → φ`, take a one-world dead-end model. It has no accessibility
arrows, and every atom is false at its only world.

```lean
private abbrev deadEndCountermodel : @Model Φ :=
  { S := Fin 1
    R := fun _ _ => False
    V := fun _ _ => False }
```

```diagram (cssWidth := "10em") (texWidth := "10em")
Model.diagram (deadEndCountermodel (Φ := Nat))
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (□ₜφ →ₜ φ) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := deadEndCountermodel
  refine ⟨M, ?_⟩
  intro hAll
  have hp := hAll 0
  exact hp (fun _ hR => False.elim hR)
```

For $`◇⊤`, the countermodel is the same dead-end model.

```diagram (cssWidth := "10em") (texWidth := "10em")
Model.diagram (deadEndCountermodel (Φ := Nat))
```

```lean
example : ⊭ˢ (◇ₜ⊤ₜ : L Φ) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := deadEndCountermodel
  refine ⟨M, ?_⟩
  intro hAll
  have hDia := hAll 0
  rcases (M.satisfies_dia 0 ⊤ₜ).mp hDia with
    ⟨_, hR, _⟩
  exact hR
```

For $`□(φ → ψ) → (□φ → ◇ψ)`, use the dead-end model once more.

```diagram (cssWidth := "10em") (texWidth := "10em")
Model.diagram (deadEndCountermodel (Φ := Nat))
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (□ₜ(φ →ₜ ψ) →ₜ (□ₜφ →ₜ ◇ₜψ)) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := deadEndCountermodel
  refine ⟨M, ?_⟩
  intro hAll
  have h := hAll 0
  have hDia := h
    (fun _ hR => False.elim hR)
    (fun _ hR => False.elim hR)
  rcases (M.satisfies_dia 0 ψ).mp hDia with
    ⟨_, hR, _⟩
  exact hR
```

For $`◇φ → □φ`, use a model where w₀ can access both worlds, including
itself. The atom φ is true at w₁ but false at w₀.

```lean
private abbrev branchCountermodel (p₀ : Φ) : @Model Φ :=
  { S := Fin 2
    R := fun w _ => w = 0
    V := fun p w => p = p₀ ∧ w = 1 }
```

```diagram (cssWidth := "16em") (texWidth := "16em")
Model.diagram (branchCountermodel (Φ := Nat) 0)
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (◇ₜφ →ₜ □ₜφ) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := branchCountermodel φ₀
  refine ⟨M, ?_⟩
  intro hAll
  have h := hAll 0
  have hpDia : M ⊨[0] ◇ₜφ := by
    apply (M.satisfies_dia 0 φ).mpr
    exact ⟨1, rfl, rfl, rfl⟩
  have hpFalse := h hpDia 0 rfl
  exact Fin.zero_ne_one hpFalse.2
```

For the disjunction of boxes, use four worlds. The two branches from w₀ make
different disjuncts fail; the extra successor w₃ of w₂ makes ψ true there but
φ false.

```lean
private abbrev fourWorldCountermodel (q₀ : Φ) : @Model Φ :=
  { S := Fin 4
    R := fun w v =>
      (w = 0 ∧ v = 1) ∨
      (w = 0 ∧ v = 2) ∨
      (w = 2 ∧ v = 3)
    V := fun p w => p = q₀ ∧ w = 3 }
```

```diagram (cssWidth := "28em") (texWidth := "28em")
Model.diagram (fourWorldCountermodel (Φ := Nat) 1)
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (□ₜ(□ₜφ →ₜ ψ) ∨ₜ □ₜ(□ₜψ →ₜ □ₜφ)) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := fourWorldCountermodel ψ₀
  refine ⟨M, ?_⟩
  intro hAll
  have h := (M.satisfies_or 0 _ _).mp (hAll 0)
  cases h with
  | inl hleft =>
      have himp := hleft 1 (Or.inl ⟨rfl, rfl⟩)
      have hpBox : M ⊨[1] □ₜφ := by
        intro v hR
        rcases hR with hR | hR | hR <;> omega
      have hqLeft := himp hpBox
      exact (by decide : (1 : Fin 4) ≠ 3) hqLeft.2
  | inr hright =>
      have himp := hright 2 (Or.inr (Or.inl ⟨rfl, rfl⟩))
      have hqBox : M ⊨[2] □ₜψ := by
        intro v hR
        rcases hR with hR | hR | hR
        · omega
        · omega
        · exact ⟨rfl, hR.2⟩
      have hpBox := himp hqBox
      have hpEnd := hpBox 3 (Or.inr (Or.inr ⟨rfl, rfl⟩))
      exact schema_atoms_ne hpEnd.1
```

For $`□(φ ∨ ψ) → (□φ ∨ □ψ)`, use a model in which every world accessible
from w₀ satisfies at least one of φ and ψ, but neither atom is true at every
accessible world.

```lean
private abbrev splitCountermodel (p₀ q₀ : Φ) : @Model Φ :=
  { S := Fin 2
    R := fun w _ => w = 0
    V := fun p w =>
      (p = p₀ ∧ w = 1) ∨
      (p = q₀ ∧ w = 0) }
```

```diagram (cssWidth := "16em") (texWidth := "16em")
Model.diagram (splitCountermodel (Φ := Nat) 0 1)
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (□ₜ(φ ∨ₜ ψ) →ₜ (□ₜφ ∨ₜ □ₜψ)) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := splitCountermodel φ₀ ψ₀
  refine ⟨M, ?_⟩
  intro hAll
  have h := hAll 0
  have hpqBox : M ⊨[0] □ₜ(φ ∨ₜ ψ) := by
    intro v _
    apply (M.satisfies_or v _ _).mpr
    fin_cases v
    · exact Or.inr (Or.inr ⟨rfl, rfl⟩)
    · exact Or.inl (Or.inl ⟨rfl, rfl⟩)
  have hpOrq := (M.satisfies_or 0 _ _).mp (h hpqBox)
  cases hpOrq with
  | inl hpBox =>
      have hpFalse := hpBox 0 rfl
      rcases hpFalse with ⟨_, hfalse⟩ | ⟨hbad, _⟩
      · exact Fin.zero_ne_one hfalse
      · exact schema_atoms_ne hbad
  | inr hqBox =>
      have hqTrue := hqBox 1 rfl
      rcases hqTrue with ⟨hbad, _⟩ | ⟨_, htrue⟩
      · exact schema_atoms_ne hbad.symm
      · exact Fin.zero_ne_one htrue.symm
```

Finally, use a reflexive one-world model for the Löb schema. The atom φ is
false at w₀, and the loop records that w₀ is accessible from itself.

```lean
private abbrev reflexiveCountermodel : @Model Φ :=
  { S := Fin 1
    R := fun _ _ => True
    V := fun _ _ => False }
```

```diagram (cssWidth := "10em") (texWidth := "10em")
Model.diagram (reflexiveCountermodel (Φ := Nat))
```

```lean
open scoped ExampleFormulas in
example : ⊭ˢ (□ₜ(□ₜφ →ₜ φ) →ₜ □ₜφ) := by
  apply schema_not_valid_of_not_valid
  apply not_valid_iff_countermodel.mpr
  let M : @Model Φ := reflexiveCountermodel
  refine ⟨M, ?_⟩
  intro hAll
  have h := hAll 0
  have hAntecedent :
      M ⊨[0] □ₜ(□ₜφ →ₜ φ) := by
    intro v _ hpBox
    exact hpBox 0 trivial
  exact h hAntecedent 0 trivial
```

end Examples
:::

3) Show that $`◇⊤` and schema $`□φ → ◇φ` share the same models. i.e
$`∀ M, (M ⊨ᵐ ◇⊤) ↔ (M ⊨ᵐˢ □φ → ◇φ)` {margin}[In other words, these are two
different ways of expressing the same property of models, or as we will see later,
equivalent ways of writing the D axiom.]

:::details "Solution"
```lean
example : ∀ M : @Model Φ, (M ⊨ᵐ ◇ₜ⊤ₜ) ↔ (M ⊨ᵐˢ (□ₜφ →ₜ ◇ₜφ)) := by
  sorry
```
:::

4) Exhibit a frame that validates □⊥. i.e., prove $`∃ F, F ⊨ᶠ □⊥`.
:::details "Solution"
```lean
example : ∃ F, F ⊨ᶠ (□ₜ⊥ₜ : L Φ) := by
  sorry
```
:::

## Properties of Valuation

:::theorem "Model.valuation_agrees"


```lean
theorem Model.valuation_agrees (M : @Model Φ) (w : M.S) (A : L Φ)
(V : QuasiAtomicSubformulaValuation A)
(hV : ∀ B hqa hB, V B hqa hB = (M ⊨[w] B)) :
((⟦A⟧ V) ↔ M ⊨[w] A) := by
  induction A with
  | atom p =>
      exact iff_of_eq (hV (L.atom p) (by simp) (by simp))
  | bot => rfl
  | box A =>
      exact iff_of_eq (hV (L.box A) (by simp) (by simp))
  | imp A B ihA ihB =>
      simp only [LiftedQuasiAtomicValuation,
        Model.satisfies]
      rw [ihA V.left, ihB V.right]
      · intro C hqa hC
        exact hV C hqa (by simp [hC])
      · intro C hqa hC
        exact hV C hqa (by simp [hC])
```
:::

5) Show the following. (1) If a formula is a tautology, it holds in any model
(i.e. it is valid, $`M ⊨ᵐ φ` for all $`M`) . (2) If $`M ⊨ᵐ φ → ψ` and $`M ⊨ᵐ φ`
then $`M ⊨ᵐ ψ`. (3) if $`M ⊨ᵐ φ` then $`M ⊨ᵐ □φ`.
```lean
theorem tautology_holds_in_all_models {φ : L Φ} :
φ.isTautology → ∀ M, (M ⊨ᵐ φ) := by
  classical
  intro hφ M w
  let V : QuasiAtomicSubformulaValuation φ := λ B _ _ => M ⊨[w] B
  have hV := hφ V
  exact (M.valuation_agrees w φ V
    (by intros; rfl)).mp hV

example : ∀ M : @Model Φ, (M ⊨ᵐ (φ →ₜ ψ)) ∧ (M ⊨ᵐ φ) → (M ⊨ᵐ ψ) := by
  sorry

example : ∀ M : @Model Φ, (M ⊨ᵐ φ) → (M ⊨ᵐ □ₜφ) := by
  sorry
```

6) Show that the above hold for frames as well. i.e.
(1) If a formula is a tautology, it holds in any frame,
(2) If $`F ⊨ᶠ φ → ψ` and $`F ⊨ᶠ φ` then $`F ⊨ᶠ ψ`.
(3) if $`F ⊨ᶠ φ` then $`F ⊨ᶠ □φ`.
```lean
example : ∀ F : Frame, (⊨ φ) → (F ⊨ᶠ φ) := by
  sorry

example : ∀ F : Frame, (F ⊨ᶠ (φ →ₜ ψ)) ∧ (F ⊨ᶠ φ) → (F ⊨ᶠ ψ) := by
  sorry

example : ∀ F : Frame, (F ⊨ᶠ φ) → (F ⊨ᶠ □ₜφ) := by
  sorry


```

# Ancestral and Descendant Worlds

Given a frame $`F = (S, R)` and a world $`w \in S`, we define the
reflexive transitive closure of $`R` as follows. We begin by defining the
$`n`-step accessibility relation $`R^n` for each natural number $`n`.
$$`
R^0(w, v) \quad\text{iff}\quad w = v
R^{n+1}(w, v) \quad\text{iff}\quad R(w, v) \vee \exists u, R(w, u) \wedge R^n(u, v)
`

```lean
@[simp]
def Frame.R_n (F : Frame) : Nat → F.S → F.S → Prop
| 0, w, v => w = v
| n+1, w, v => F.R w v ∨ ∃ u, F.R w u ∧ Frame.R_n F n u v
```
From this we define the reflexive transitive closure $`R^*` as existance
of an $`n` such that $`R^n(w, v)` holds.

```lean
@[simp]
def Frame.R_Star (F : Frame) (w v : F.S) : Prop :=
  ∃ n, Frame.R_n F n w v
```

## Exercises

1) R^1 = R. Show that for any frame F, any world w, and any world v, we have
$`R^1(w, v) \quad\text{iff}\quad R(w, v)`
2) if $`R^*(w, v)` holds, then there exists a sequence of worlds
$`w_0, w_1, \dots, w_n` (with $`w_0 = w` and $`w_n = v`) such that
for all $`i < n, R(w_i, w_{i+1})` holds.
3) $`R^*` is reflexive and transitive.
4) Let $`T` be any transitive relation on the set of worlds $`S`.
Show that if $`R \subseteq T`, then $`R^* \subseteq T`. i.e $`R^*` is the
smallest reflexive and transitive relation on $`S` containing $`R`.
5) If $`S = ℤ` and $`R = {(w, w+1) | w ∈ S}`, what is $`R^*`? Provide the
relation `Q : ℤ → ℤ → Prop` and show that $`R^* = Q`.

```lean
theorem Frame.R_n.R_1_eq_R (F : Frame) (w v : F.S) : F.R_n 1 w v ↔ F.R w v := by
  simp only [R_n, exists_eq_right, or_self]

theorem Frame.R_Star.exists_sequence (F : Frame) (w v : F.S) :
F.R_Star w v ↔ ∃ n : Nat, ∃ (w_seq : Fin (n+1) → F.S),
  w_seq 0 = w ∧ w_seq ⟨n, by simp⟩ = v ∧
  ∀ i : Fin n, F.R (w_seq ⟨i.1, by simp⟩) (w_seq ⟨i.1 + 1, by simp⟩) := by
  sorry

@[simp]
theorem Frame.R_Star.refl (F : Frame) (w : F.S) : F.R_Star w w := by
  simp only [R_Star]
  exact ⟨0, rfl⟩

theorem Frame.R_Star.trans (F : Frame) (w u v : F.S) :
F.R_Star w u → F.R_Star u v → F.R_Star w v := by
  simp
  intro n H1 m H2
  sorry
```


# Generated Submodels

Given the previously defined reflexive transitive closure of the
accessibility relation, we can define the submodel generated by a world
in a model.

Intuitively, the submodel generated by a world $`w`$ consists of all worlds
that are accessible from $`w`$ (including $`w`$ itself), along with the
restriction of the accessibility relation and valuation to these worlds.

:::definition "Generated Submodel"
Given a model $`M = (S, R, V)` and a world $`w \in S`, we define the _submodel
 of $`M` generated by $`w`_ as the model $`M_w = (S_w, R_w, V_w)` where
- $`S_w = {v ∈ S | R^*(w, v)}` is the set of worlds accessible from $`w`
(including $`w` itself),
- $`R_w = R \cap (S_w \times S_w)` is the restriction of $`R` to $`S_w`,
- $`V_w(p) = V(p) \cap S_w` for each propositional variable $`p`.

```lean

-- The type of worlds accessible from a given world w in a frame F.
abbrev Frame.S_sub (F : Frame) (w : F.S) : Type :=
  {u : F.S // F.R_Star w u}

abbrev Frame.R_sub (F : Frame) (w : F.S) (u v : F.S_sub w) : Prop :=
  F.R u v

abbrev Model.V_sub (M : @Model Φ) (w : M.S) (p : Φ) (v : M.S_sub w) : Prop :=
  M.V p v

def Frame.subframe (F : Frame) (w : F.S) : Frame := {
  S := F.S_sub w,
  -- S is nonempty because w is in S and R^* is reflexive
  S_nonempty := by exists w; apply Frame.R_Star.refl
  R := F.R_sub w
}

def Model.submodel (M : @Model Φ) (w : M.S) : @Model Φ := {
  toFrame := M.subframe w,
  V := M.V_sub w
}

```

:::

:::theorem "The Submodel Lemma"
For any model $`M = (S, R, V)`, any $`w \in S`, and any world $`v \in S_w`
We have that $`M_w ⊨_v φ` if and only if $`M ⊨_v φ`.
```lean
theorem Model.submodel_lemma
(M : @Model Φ) {φ : L Φ} {w : M.S} {v : M.S_sub w} :
(M.submodel w ⊨[v] φ) ↔ M ⊨[v] φ := by
  induction φ generalizing v
  . case atom p =>
    simp_all only [satisfies, Frame.R_Star]
    obtain ⟨val, property⟩ := v
    simp_all only [Frame.R_Star]
    rfl
  . case bot =>
    simp_all only [satisfies]
  . case imp φ ψ ihφ ihψ =>
    simp_all only [satisfies]
  . case box φ ih =>
    constructor
    · intro h u hvu
      have hu : M.R_Star w u := by
        exact Frame.R_Star.trans M.toFrame w v u v.2 ⟨1, Or.inl hvu⟩
      exact (@ih ⟨u, hu⟩).mp (h ⟨u, hu⟩ hvu)
    · intro h u hvu
      exact (@ih u).mpr (h u.1 hvu)
```

From this we get three corolaries:
1) If a formula is true in a model, then it is true in any submodel.
$$`M ⊨ᵐ φ \implies M_w ⊨ᵐ φ`
2) A formula is true in a model iff it is true in all of its submodels.
$$`M ⊨ᵐ φ \iff ∀w, M_w ⊨ᵐ φ`
3) A formula is valid in a frame iff it is valid in all of its subframes.
$$`F ⊨ᶠ φ \iff ∀w, F_w ⊨ᶠ φ`
```lean

lemma Model.submodel_satisfies_from_satisfies
(M : @Model Φ) {φ : L Φ} {w : M.S} :
(M ⊨ᵐ φ) → (M.submodel w ⊨ᵐ φ) := by
  intro h v
  exact M.submodel_lemma.mpr (h v.1)

lemma Model.satisfies_iff_all_submodel_satisfies
(M : @Model Φ) {φ : L Φ} :
(M ⊨ᵐ φ) ↔ ∀w, M.submodel w ⊨ᵐ φ := by
  constructor
  · intro h w
    exact M.submodel_satisfies_from_satisfies h
  · intro h v
    have h' := h v
    simp at h'
    have h'' := h' ⟨v, by apply Frame.R_Star.refl⟩
    exact M.submodel_lemma.mp h''

lemma Frame.valid_iff_all_subframe_valid
(F : Frame) {φ : L Φ} :
(F ⊨ᶠ φ) ↔ ∀w, F.subframe w ⊨ᶠ φ := by
  simp only [L.valid_in_frame]
  constructor
  · intro h w M hM
    sorry
  . intro h M hM
    sorry
```
:::

# P-morphisms

:::definition "p-Morphisms"
Let $`M_1 = (S_1, R_1, V_1)` and $`M_2 = (S_2, R_2, V_2)`.
A function $`f:S_1 → S_2` satisfying the following three
conditions is called a _p-morphism_ from $`M_1` to $`M_2`.
$$`
\begin{aligned}
R_1(s,t) &→ R_2(f(s), f(t)) \\
R_2(f(s), u) &→ ∃t, R_1(s,t) ∧ f(t) = u \\
V_1(p, s) \iff V_2(p, f(s))
\end{aligned}
`
A function satisfying only the first two conditions is said to be
a p-morphism on frames.
```lean

class pMorphismF {F1 F2 : Frame} (f : F1.S → F2.S) : Prop where
  c1 {s t : F1.S} : F1.R s t → F2.R (f s) (f t)
  c2 {s : F1.S} {u : F2.S} : F2.R (f s) u → ∃t, F1.R s t ∧ f t = u

class pMorphism {M1 M2 : @Model Φ} (f : M1.S → M2.S) : Prop
extends pMorphismF f where
  c3 {p : Φ} {s : M1.S} : M1.V p s ↔ M2.V p (f s)
```
:::


:::theorem "p-Morphism Lemma"

For any formula $`φ`, two models $`M_1, M_2`, world $`w ∈ S_1`
and p-Morphism between them $`f`,
we have that $$`M_1 ⊨_w φ ↔ M_2 ⊨_{f(w)} φ`

```lean
theorem pMorphism.satisfies_iff
{M1 M2 : @Model Φ} {f : M1.S → M2.S} [pMorphism f] {φ : L Φ} {w : M1.S} :
(M1 ⊨[w] φ) ↔ (M2 ⊨[f w] φ) := by
  induction φ generalizing w
  . case atom p =>
    simp_all only [Model.satisfies]
    apply Iff.intro
    · intro a
      apply pMorphism.c3.mp a
    · intro a
      apply pMorphism.c3.mpr a
  . case bot =>
    simp_all only [Model.satisfies]
  . case imp a1 a2 ih1 ih2 =>
    simp_all only [Model.satisfies]
  . case box a1 ih =>
    simp_all only [Model.satisfies]
    apply Iff.intro
    · intro a v a_1
      have ⟨_, hw⟩ := pMorphismF.c2 a_1
      obtain ⟨left, right⟩ := hw
      subst right
      simp_all only
    · intro a v a_1
      apply a
      exact pMorphismF.c1 a_1
```

:::

:::definition "p-Morphic Image"
For two frames $`F_1` and $`F_2` we say $`F_1` is the _p-morphic image_ of
$`F_2` if there exists a surjective p-morphism $`f` between them.

```lean
@[simp]
def pMorphicImage (F1 F2 : Frame) : Prop :=
∃ (f : F1.S → F2.S), pMorphismF f ∧ Function.Surjective f
```
:::

This then leads us to the following

:::theorem "p-Morphism Lemma 2"

If $`F_2` is a p-morphic image of $`F_1` then for any formula $`f`
$$`(F_1 ⊨ᶠ φ) → (F_2 ⊨ᶠ φ)`

```lean
-- TODO: rename
theorem p_morphism_lemma_2 {F1 F2 : Frame} {H : pMorphicImage F1 F2} {φ : L φ}:
F1 ⊨ᶠ φ → F2 ⊨ᶠ φ :=
  sorry
```
:::

## Exercises

Given the follwing two frames $`F1 := ({0, 1}, λxy.\texttt{True})` and
$`F2 := ({0}, λxy.\texttt{True})` show that
$$`
\begin{aligned}
(F_1 ⊨ᶠ φ) &→ (F_2 ⊨ᶠ φ) \\
((ℕ, <) ⊨ᶠ φ) &→ (F_1 ⊨ᶠ φ) \\
\end{aligned}
`

:::details "Solutions"
Both follow directly from our lemma.
We can prove both of these by showing that $`F2` is the p-morphic image
of $`F1` and $`F1` is the $`F1` is the p-morphic image of (ℕ, <). We do this
by providing an explicit p-morphism.
```lean
--TODO: I speed ran this proof and it needs cleanup
example : (⟨Fin 2, λ _ _ => True⟩ ⊨ᶠ φ) → (⟨Fin 1, λ _ _ => True⟩ ⊨ᶠ φ) := by
  apply p_morphism_lemma_2
  exists (λ _ => 0)
  constructor
  constructor
  simp;
  intro s u a
  simp_all only [true_and, exists_const]
  ext : 1
  simp_all only [Fin.val_eq_zero]
  simp [Function.Surjective]

example : (⟨ℕ, (· < ·)⟩ ⊨ᶠ φ) → (⟨Fin 2, λ _ _ => True⟩ ⊨ᶠ φ) := by
  apply p_morphism_lemma_2
  -- Bad selection of F
  exists (λ n => match n with | 0 => 0 | n + 1 => 2)
  constructor
  . case left =>
    constructor
    . case c1 =>
      intro s t a
      simp_all only
    . case c2 => sorry
  . case right =>
    simp [Function.Surjective]
    constructor
    . case left => exists 0
    . case right => sorry
```
:::

# Frame Conditions

TODO, most important section

# Proof Theory

:::definition "Logic"
Given a denumerable set of atomic formulae $`Φ`, a logic is any subset
$`Λ ⊆ Fma(\Φ)` such that:
1) $`Λ` includes all tautologies
2) $`Λ` is closed under _the rule of detachment_ i.e
  $$`φ ∈ Λ, φ → ψ ∈ Λ \implies ψ ∈ Λ`

```lean
class Logic [Denumerable Φ] (Λ : Set (L Φ)) : Prop where
  all_tauto {φ : L Φ} : φ.isTautology → φ ∈ Λ
  detachment {φ ψ : L Φ} : φ ∈ Λ ∧ (φ →ₜ ψ) ∈ Λ → ψ ∈ Λ
```
:::

Some examples of logics are
1) The set of all tautologies, which we call $`PL`.
2) For any class of frames $`C`, the set of all formulae valid in
   all frames in $`C` i.e the set $`\{ φ | ∀ F ∈ C, F ⊨ᶠ φ \}`
3) The set of all formulae itself.
4) The intersection of any collection of logics $`\{Λ_i | i ∈ I\}`.
  $$`\bigcap_{i ∈ I} Λ_i`

```lean


abbrev PL (Φ : Type) [Denumerable Φ] : Set (L Φ) := { φ | ⊢ₜ φ }

instance PL.instLogic : Logic (PL Φ) where
  all_tauto := by exact id
  detachment := by
    rintro φ ψ ⟨hφ, hφψ⟩ Vψ
    let V : QuasiAtomicSubformulaValuation (φ →ₜ ψ) :=
      fun χ hqa _ => if hχ : χ ∈ S[ψ] then Vψ χ hqa hχ else False
    have h := hφψ V (hφ V.left)
    apply (LiftedQuasiAtomicValuation.congr (Φ := Φ) ψ V.right Vψ ?_).mp h
    intro χ hqa hχ hχ'
    simp only [QuasiAtomicSubformulaValuation.right, L.isQuasiAtomic,
      L.subformulae, Finset.singleton_union, dite_else_false, hχ',
      exists_true_left, V]

instance (C : Set Frame) : Logic { φ : L Φ | ∀ F ∈ C, F ⊨ᶠ φ } where
  all_tauto := by
    intros φ Hφ F HF
    sorry

  detachment := by sorry


theorem Logic.intersection [Denumerable Φ] (Λ : I → Set (L Φ))
[∀ i, Logic (Λ i)] :
  Logic (⋂ i, Λ i) := by
  sorry
```

Since the intersection of any collection of logics is itself a logic, we can
define the _smallest logic_ containing a set of formulae $`Γ`$ as the
intersection of all logics containing $`Γ`$.


:::definition "Smallest Logic"
Given a set of formulae $`Γ ⊆ Fma(Φ)`$, the _smallest logic_ containing
$`Γ`$ is the intersection of all logics containing $`Γ`$.

From this, we note that PL is the smallest logic, and FBA is the largest,
in the sense that any logic $`Λ` satisfies $`PL ⊆ Λ ⊆ FBA`.
```lean
lemma Logic.PL_subset (Λ : Set (L Φ)) [Logic Λ] : (PL Φ) ⊆ Λ := by
  sorry

```

:::
